### ISSUE TITLE
Remove accessories issue

### ISSUE THREAD

**Issue by mightChamp** [HomeSpan/HomeSpan#110]
Hello,

I have 3 Lightbulb, named L1, LB2 and LB3. I  added LB1, LB2 and LB3 accessories, and it reflects on Home App as expected. Then I removed LB1 from code and flash the code to ESP32. But in Home App LB3 is removed instead of LB1, and now when I operate LB1 it updates LB2 and similarly LB2 updates LB3 lightbulb. So functionality is reflected but name on Home app doesn't changed. 
But when I unpaired and paired again ESP32, then Lightbulb name changed to LB2 and LB3.

Please help me to resolve this issue.

Thank You

**Comment by HomeSpan** [comment]
In principle HomeKit should properly update things when you make changes to the Accessories as you've described.  However, in practice HomeKit caches a lot of information and may not properly reflect updates.  As you found, one way of resynchronizing HomeKit is to unpair and re-pair the device.  Unfortunately, even this sometimes does not work.  If that happens then I recommend after unpairing you reset the HomeKit device ID on the ESP32 using the 'H' command.  When you then re-pair, the ESP32 will appear to HomeKit as a completely new device.

The root cause of this behavior is that HomeKit keeps track of Accessories according to their Accessory ID (AID) number.  HomeSpan automatically produces these numbers sequentially, starting with an aid=1 for the first `new SpanAccessory()`, an aid=2 for the second, etc.  This means if you delete the second Accessory you defined, HomeKit will think that the third one in your list is now the second.  This creates the inconsistencies you've noted.

To avoid generating these types of inconsistencies when developing a new sketch, HomeSpan allows you to optionally specify the aid of an Accessory in the constructor as such: `new SpanAccessory(5)`.  This ensures that HomeKit will always properly link to the same Accessory each time even if you delete or add new Accessories to your sketch.  The AID argument can be any value from 1 through 2^32-1, with the only requirement that the very first Accessory must have an aid=1 (the first Accessory is usually the bridge).

For example, if your initial sketch specifies aid values of 11, 12, and 13 to represent the Accessories for LB1, LB2, and LB3, you should find that if you delete LB2, HomeKit will properly identify the other two Accessories as LB1 and LB3 since it will find aid values of 11 and 13.

Hope this helps explains the behavior you're seeing and provides a method for addressing.

**Comment by mightChamp** [comment]
Thanks for great explanation I will try your suggestions.
