### ISSUE TITLE
When paired without accessories(i.e. lightbulb or switch) with Home app, and then after added accessories not shown up and also pairing option is not available

### ISSUE THREAD

**Issue by mightChamp** [HomeSpan/HomeSpan#112]

**Comment by HomeSpan** [comment]
Are you pairing as bridge with the first Accessory being non-operational (no light or switch, just the name and required version characteristic)?  Or are you pairing with no Accessories at all (I don't think that is allowed).

**Comment by mightChamp** [comment]
I am paring as bridge without light or switch as shown below:
Case 1:
`new SpanAccessory();  
    new DEV_Identify("Bridge #1","HomeSpan","123-ABC","HS Bridge","0.9",3);
    new Service::HAPProtocolInformation();
      new Characteristic::Version("1.1.0");`

then I add accessories and flash code again as shown below:

Case 2:
`new SpanAccessory();  
    new DEV_Identify("Bridge #1","HomeSpan","123-ABC","HS Bridge","0.9",3);
    new Service::HAPProtocolInformation();
      new Characteristic::Version("1.1.0");
  
  // Defines an ON/OFF LED Accessory attached to pin 16

  new SpanAccessory();                                                          
    new DEV_Identify("On/Off LED","HomeSpan","123-ABC","20mA LED","0.9",0);
    new DEV_LED(16);

  // Defines a Dimmable (PWM-driven) LED Accessory attached to pin 17
  
  new SpanAccessory();                                                        
    new DEV_Identify("Dimmable LED","HomeSpan","123-ABC","20mA LED","0.9",0);       
    new DEV_DimmableLED(17); `

With case 1 I paired with Home app,
and then I flash case 2 code, In Home app no accessories is shown. and ESP32 shows already paired, So I can't unpair from app and pair again, and no accessories shown up on app, I have to unpair from command, and then pair again.

**Comment by HomeSpan** [comment]
I reviewed the HAP documentation and it is not clear on whether a bridge must have at least one non-bridge Accessory.  Based on what you've described, it seems that may be the case, and that in order to add more Accessories to the bridge, you need to start with at least one.

In your above example, if Case 1 includes two `new Accessory()` calls (one for the bridge and one for an LED), and Case 2 is the same as Case 1 but includes a third `new Accessory()` for the second LED, you should see HomeKit update from just showing one LED to showing both LEDs when you reflash with Case 2.

**Comment by mightChamp** [comment]
Ok thanks
