### ISSUE TITLE
Can you provider a sample to control temperature of lights?

### ISSUE THREAD

**Issue by paultang** [HomeSpan/HomeSpan#116]
You have providers a lot of great sample of lights. Dimmer LED and RGB light.  Now I got a light panel which contain RGB and CW and WW.  Could you provider a new sample which integrate both RGB and white control . thanks.

**Comment by HomeSpan** [comment]
The HomeSpan configuration for a white-balance light bulb would be something like this:

```C++
    new Service::LightBulb();
      new Characteristic::On();
      new Characteristic::Brightness();
      new Characteristic::ColorTemperature();
```

where the allowable values for ColorTemperature are 140 through 500, which are in mirek units, defined as M=1,000,000/K, where K is color temperature in Kelvin.  This yields a temperature range of 7,142K through 2,000K.  Not sure why HAP insists on using the inverse mired scale instead of just temperature in Kelvins.  Note that the HAP R2 guide seems to have a misprint and indicates the range of ColorTemperature is 50-400 (I have verified that anything less than 140 produces an HomeKit error).

I don't have any color-temperature bulbs so unfortunately can't provide any guidance on the backend code needed to control them with ESP32 pins.  If you can send me a link with specs for the light panel I can take a look.

**Comment by paultang** [comment]
i bought this [one.](https://www.aliexpress.com/item/10000403709546.html?spm=a2g0o.productlist.0.0.3ec93e83NckB7f&algo_pvid=921a9d66-3bd1-4804-b969-cdf792980794&aem_p4p_detail=202107250310413007512497559000001173975&algo_exp_id=921a9d66-3bd1-4804-b969-cdf792980794-0). There are 5 pins, three pins is for RGB.  and Two pins for Cold and Warm White.  Can you add them to the light sample.  Thanks

**Comment by paultang** [comment]
i did as you same. it works, thanks.
