### ISSUE TITLE
2 questons regarding HomeSpan

### ISSUE THREAD

**Issue by Adajaken** [HomeSpan/HomeSpan#118]
1. For those esp32 module which has been connected, even if I factory reset it, it keeps requesting ‘enter password’ when re-connecting to hotspot HomeSpan. What’s the password?

2. How to solve below?
![294BF817-F768-4834-B441-3A7355586FC4](https://user-images.githubusercontent.com/85116753/127262916-ec0120d5-65b2-4315-bbc3-a15601ac9357.jpeg)

Thanks in advance.

**Comment by HomeSpan** [comment]
I'm not sure I understand your first question - you only connect to the hotspot once in order to enter your WiFi Credentials.  Once done, there is no need to connect back to the hotspot.  Default password is *homespan*.  See the User Guide for complete details.

For your second question, this will occur if some component on your network is sending data to HomeSpan that it does not recognize.  It is not uncommon for home network routers to ping devices for different information.  If you type "L2" in the CLI you will be able to see the IP address of the device that is sending this malformed HTTP request along with the specific request.  Unless this interferes with normal HomeSpan operations this can be ignored.
