### ISSUE TITLE
Cannot set dynamic Accessory Name?

### ISSUE THREAD

**Issue by unreality** [HomeSpan/HomeSpan#119]
According to the examples:

`new Characteristic::Name("My Table Lamp");      // Name of the Accessory, which shows up on the HomeKit "tiles", and should be unique across Accessories`

But if we try to set the name dynamically eg:

```c++
char name[64];
sprintf(name, "ESP Accessory %08X", (uint32_t)ESP.getEfuseMac());
new Characteristic::Name(name); 
```

This causes the accessory to give the error 'Discovery Failed' when adding. It looks like HomeSpan handles the dynamic name fine (listing characteristics in the console etc), up until it needs to send the discovery info back and renders the JSON:

```json
...
{"iid":2,"type":"23","value":"⸮G⸮O","format":"string","perms":["pr"]}
...
```

Can the JSON render be fixed so that dynamic names are rendered correctly?

**Comment by HomeSpan** [comment]
When passing char arrays variables, such as in your code snippet above, HomeSpan retains the pointer and *does not* make a new copy of the string. This saves a lot of space, especially since in most use cases the strings are static.  However, it is still possible to pass a dynamic string, as long as the pointer to the memory does not go out of scope leaving the memory free for other uses.

In your snippet above, is name[64] a local variable defined within a function?  If so, as soon as the function returns, the memory associated with name (which is likely on the stack) will be reused and overwritten by other processes, resulting in what you are seeing.

The solution is to assign some permanent storage to name - this can be done by:

* creating name as a global variable (not the best solution in large-scale programming, but fine for a short sketch), or
* using "new" to allocate memory with a dynamic pointer so the memory is retained even after the pointer to it goes out of scope, or
* declaring name as an object variable as part of a child class containing all the logic and parameters of a HomeSpan Service.

An example of using the first method can be found in the [ProgrammableHub Project](https://github.com/HomeSpan/ProgrammableHub).

**Comment by unreality** [comment]
Thanks for the scopes explanation, moving the variable into a global scope works.
