### ISSUE TITLE
Idea: HTTP Webserver endpoints

### ISSUE THREAD

**Issue by danricho** [HomeSpan/HomeSpan#129]
This is just an idea for consideration.

Perhaps the ESP32 webserver library could be integrated at an accessory level to provide 2 endpoints for easy integration into other systems:

1.  `<ip>:80/<accessoryID>/get` could return the targeted accessory's characteristics and values as JSON
2. `<ip>:80/<accessoryID>/set/<characteristicID>/<value>` could set the targeted accessory's target characteristic to a value

I have implemented this for a garage door accessory, based on [HomeSpan/ProgrammableHub](https://github.com/HomeSpan/ProgrammableHub). Just like that example, I am using global variables to pass states between the webserver and the HomeSpan objects.

---

In lieu of that, I'm wondering if there are built in public methods to retrieve or set a HomeSpan accessory's characteristic or is the only method to create global variables and manually keep them in sync within the accessory functions?

for example in https://github.com/HomeSpan/HomeSpan/blob/master/examples/13-TargetStates
is there a clean way for me to do a `current->getVal();` from within the main `loop()` in the `.ino` file or what is the best way to make a method to return that value? Unfortunately I'm not great at the OOP so I'm unsure how to address the nested objects... I'm thinking something like for example (I know it's wrong, for explanation only):

```
void loop(){
  homeSpan.poll();
  Serial.print(DEV_GarageDoor->current->getVal()); // how is this actually done?
} // end of loop()

```

**Comment by danricho** [comment]
I'm sorry, this should have been a discussion. Will use that from now on!

**Comment by HomeSpan** [comment]
The HAP spec generally prohibits direct web access (or any other "out-of-band" access) to HomeKit Accessories since that would defeat the underlying security of HAP (which in many ways is what makes HAP so complicated).  In order to stay true to HAP I did not add any out-of-band hooks to the library itself.

However, this can be done from the application layer by creating a separate web server, as you saw in the ProgrammableHub project.  By separating this out from the library, HomeSpan itself can strictly adhere to HAP protocols, but users can add their own alternative access points if desired.

Regarding the ability to directly access Characteristics from the *.ino file, there are many ways this can be done - the key is that you need to name the Service when it is instantiated so you can call it later.  Here is a revised *.ino file based on tutorial 6 that retrieves the brightness of an LED, and prints it to the Serial Monitor whenever it is changed:

```C++
#include "HomeSpan.h" 
#include "DEV_LED.h"      

DEV_DimmableLED *led1;        // GLOBAL POINTER TO STORE DIMMABLE LED SERVICE
int brightness1=0;            // GLOBAL VARIABLE TO STORE BRIGHTNESS OF LED

void setup() {
  
  Serial.begin(115200);

  homeSpan.begin(Category::Lighting,"HomeSpan LEDs");
  
  new SpanAccessory(); 
  
    new Service::AccessoryInformation();    
      new Characteristic::Name("Dimmable LED");    
      new Characteristic::Manufacturer("HomeSpan"); 
      new Characteristic::SerialNumber("123-ABC");  
      new Characteristic::Model("20mA LED");   
      new Characteristic::FirmwareRevision("0.9");  
      new Characteristic::Identify();               
      
    new Service::HAPProtocolInformation();          
      new Characteristic::Version("1.1.0");         
  
    led1=new DEV_DimmableLED(17);        // SAVE POINTER TO THIS SERVICE SO IT CAN BE USED BELOW

} // end of setup()

//////////////////////////////////////

void loop(){
  
  homeSpan.poll();

  if(led1->level->getVal() != brightness1){             // RETREIVE THE VALUE OF THE "LEVEL" CHARACTERISTIC FROM LED1
    brightness1 = led1->level->getVal();
    Serial.printf("LED1 Brightness changed to %d\n",brightness1);
  }
  
} // end of loop()
```

**Comment by danricho** [comment]
That makes a lot of sense. Thanks.

I wasn't naming the service, so that was the piece of information/knowledge I was missing.

Thanks and closing this as an "issue".
