### ISSUE TITLE
Send feedback of status of device(lightbulb) to app, after checking lightbulb actual value

### ISSUE THREAD

**Issue by mightChamp** [HomeSpan/HomeSpan#132]
I have a light Blub which is operated through ligthbulb characteristic on off. I also have a feedback mechanism from which I get bulb is actually on or off(may get damage). I want the actual status of bulb in app.

When App Send request for On, ESP32 on the pin, and send feedback of On to app, I want to first check if it is actual on and then send feedback of actual value. Can I do this?

**Comment by HomeSpan** [comment]
There are a few different ways you can accomplish this, depending on what type of feedback you are looking to provide.  The easiest method would be to check the status of the bulb in the `update()` method of your lightbulb service whenever the user requests the bulb to turn on.  If the bulb is not operating correctly, you can return a `false` instead of a `true`.  The Home App is not very smart about processing different types of error messages, so this will likely lead to a "No Response" status.  Unfortunately there is no way of producing a specific error message that someone using the Home App can digest.  The other downside of this method is that the lightbulb is only checked when the user tries to turn it on, since that's the only time the `update()` method is called.

As an alternative, you can continuously check the health of the lightbulb by adding a `loop()` method to your lightbulb service.  Within this method you can check the status of the bulb, and if it not working you can reset the On Characteristic from `true` to `false`, which will be reflected in the Home App.  See [Example 12](https://github.com/HomeSpan/HomeSpan/blob/master/docs/Tutorials.md#example-12---serviceloops) for details on how to use the `loop()` and `setVal()` methods to send notifications back to the Home App that changes the value of a characteristic.  Take care if you use this method to only send notifications back to the Home App if the status of the bulb changes.  If you send continuous notifications repeating the same status over and over you will generate a LOT of network traffic and likely cause problems for the Home App.

**Comment by mightChamp** [comment]
In update() if I return false, then I get No Response on app side, even if I set the actual value of lightbulb by setVal() function.

**Comment by HomeSpan** [comment]
Please review the HomeSpan documentation and the tutorials.  The return value of update() has nothing to do with the status of any Characteristics --- in fact there may be 5 Characteristics that are all changed in a single update() call, many of which are numerical in value.

Rather, the return value of update() reflects whether or not the update() was successful, or if there is a problem with your device.  By returning a value of false, you are telling the Home App that there is a problem with your device and the Home App request has failed (hence the Home App indicates no response).  Unless you want to send a fail signal to the Home App you should always return a true to update() as per the docs.

**Comment by mightChamp** [comment]
Ok Got it. Thanks for clarification
