### ISSUE TITLE
Disable internal pull-up

### ISSUE THREAD

**Issue by Arashinof** [HomeSpan/HomeSpan#136]
Im trying to use a ttp223 touch sensor as push button it has 2 modes, active low ( normally low output and High when touched ) And active high ( normally high and Low when touched )
How can i modify the code? to disable the internal pull-up because ttp223 normally sends high value in active high mode

![image](https://user-images.githubusercontent.com/79417601/130320932-8d9365f5-b409-4f8d-b6e8-6aeb24451d85.jpeg)
( i want use config3 )

**Comment by HomeSpan** [comment]
The code for the PushButton logic is found in *Utils.cpp*.  However, simply changing the internal pull-up won't work since all the logic that detects highs/lows would also have to be reversed.  This is doable but would break the Control Button logic --- you would have to change the Control Button so it connects to +3V (NOT +5V!) instead of ground.

All this is possible, but since your device seems to be configurable (per above), why not just use Config 3, which would match a normal pushbutton connected to ground?  You would not need to change any of the code.

One other possibility is to skip the use of `SpanButton()` completely.  SpanButton's primary purpose is to debounce physical buttons.  My guess is the ttp223 already has all of this logic since it is processing a touch switch.  In that case you can simply create a `loop()` method for your Service (see [Example 12](https://github.com/HomeSpan/HomeSpan/blob/master/docs/Tutorials.md#example-12---serviceloops)) and poll for a change from low to high on whatever pin you connect the ttp223.   This will require some logic and storage of the current state of the ttp223, but you won't need any of the debouncing logic that forms the core of `SpanButton().`

That said, your example is a good use-case and I'll try to add an option to `SpanButton()` that allows for an inversion of all the logic in a future release.

**Comment by Arashinof** [comment]
Thank you so much :))
