### ISSUE TITLE
homeSpan.begin() and M5Stack AXP192 Voltages

### ISSUE THREAD

**Issue by helo-head** [HomeSpan/HomeSpan#154]
I have an odd issue with a M5StickC Plus ESP32 device. Apparently there is some strange incompatibility between homeSpan and the M5 AXP192 code that returns the battery and bus voltages. It took me about 4 hours to determine that the issue starts immediately after I call homeSpan.begin. At that point the AXP voltage calls start returning incorrect values (about 1 - 2 volts higher than reality). Unfortunately this makes battery management difficult.

I will test this on a M5Core2 tomorrow and see if this issue is unique to the M5StickC-Plus or all the M5Stack ESP32 devices. 

Here is a sample that exhibits the problem. If I comment out homeSpan.begin the problem goes away ...  As you can see this is about the minimum HomeSpan code you can get away with ... 

#include <M5StickCPlus.h>
#include <AXP192.h>
#include <HomeSpan.h>

unsigned long currentMillis;
unsigned long previousMillis;
const unsigned long period = 5000;

void setup() {
  M5.begin();
  Serial.begin(115200);
  previousMillis=millis();
  homeSpan.begin(Category::Bridges,"HomeSpan Bridge");
} 

void loop(){
    M5.update(); 
   String output = "";

  currentMillis = millis();  //Pull current time since boot
 
 if ((currentMillis - previousMillis) >= period) {      //Check time elapsed since last update 
    output = "BatV: " + String(M5.Axp.GetBatVoltage()) + " VBUS: " + String(M5.Axp.GetVBusVoltage()) + "\n";
    Serial.print(output);
    previousMillis=millis();                             //Update previousmillis for next cycle
  }
}

**Comment by HomeSpan** [comment]
I'm unfamiliar with the M5StickC Plus but based on the pin mappings file from the Arduino-ESP32 site it seems the board exposes a limited number of GPIO pins - perhaps because other GPIO pins are being used for other functions, such as reading the battery.  I noticed that GPIO pin 21 is not defined, but HomeSpan uses that as the default pin for the control button.  If this is being used for another purpose by the M5StickC software, this could cause a problem.   HomeSpan also used pin 13 as the default for the status LED.  This pin appears to be defined for the M5 but is used for the external SPI (which may impact any devices connected via the SPI).  To see if this is the problem you can instruct HomeSpan to use different pins for the control button and the LED with the setControlPin() and setStatusPin() methods (see the API for details).

**Comment by helo-head** [comment]
Many thanks .. should have been obvious to me but sometimes the trees are not visible while looking at the forest fire. Pin 21 is used by the AXP which explains why it was interfering. I changed StatusPin to 10 which is the actual LED and the ControPinl to 26 (unused). Will probably change ControlPin to 39 (button B) at some point but right now Im using that button for troubleshooting purposes. Again, many thanks for a great product and support.
