### ISSUE TITLE
Duration time for Valve accessory

### ISSUE THREAD

**Issue by Magicot1** [HomeSpan/HomeSpan#167]
I'm having trouble with the duration characteristic of my valve (sprinkler type) accessory, the home app lets me chose the default time of activation but the timer doesn't appear and after the selected time has passed the valve doesn't turn of.

**Comment by DanielO** [comment]
I am writing a valve project and I think you need to manage the timing etc yourself.

ie when the active characteristic is set to on then store the time now plus the value of the set duration characteristic and have it turn off when time gets to then.

That said, my code does not work yet so perhaps I am doing it wrong :)

**Comment by HomeSpan** [comment]
I'll try to publish a tutorial on Irrigation systems since they present a lot of interesting features.  @DanielO, I believe you are correct - the duration settings in the Home App are only used to inform the Accessory (i.e. HomeSpan) of the desired duration.  The Accessory must handle all automation internally, and then report back to the Home App whenever the status of a valve (or the system itself) changes.  The RemainingDuration Characteristic is used to report back to the Home App how much time it left, but it should *only* be used when the schedule is interrupted (for example, the system is manually paused and then restarted), and *not* used to report back every second.

**Comment by DanielO** [comment]
Thanks, I'd be very interesting in seeing it. FWIW I wrote a similar thing for the Particle HAP a while ago (https://github.com/DanielO/Particle-HAP/tree/master/examples/sprinkler) and I want to port it to Home Span.

My work so far is https://github.com/DanielO/HKSprinkler and it seems to work OK, although I can't get the remaining duration working yet - the Home app just shows it on or off with no count down.

**Comment by DanielO** [comment]
I just debugged my code, now time remaining works fine..

**Comment by DanielO** [comment]
I take that back - it keeps resetting back to the set duration. For the Particle-HAP version I supplied a getter that calculated the remaining time but I can't see how to do that with HomeSpan.
Is it possible?

**Comment by HomeSpan** [comment]
I've just done a lot of experimenting with the HomeKit Irrigation Service and got things working reasonably well.  As expected, the HAP-R2 documentation is not fully accurate.  A few things I found:

The `In Use` and `Remaining Duration` Characteristics are needed for the Valve Service, but are completely ignored by the Irrigation Service itself.  The Home App unfortunately does not have a way of presenting `In Use` or `Remaining Duration` at the top-level of the Accessory (for example, if a schedule across multiple Valves was running).  The good news is I found that the Home App does not complain if you don't even bother creating these Characteristics for the Irrigation Service.

There is also no master switch in the Home App that toggle the `Active` Characteristic at the top-level of the Irrigation Service.  Instead, `Active` is only used at the level of each Valve Service.  However, you still need to create an `Active` Characteristic for the Irrigation Service since the Home App updates its value to 1 whenever any Valve is opened.  For whatever reason the Home App does not reset this to 0 when all the Valves are closed.  So though it is not very useful, you nevertheless *must* create an `Active` Characteristic for the Irrigation Service to prevent "No Response" errors, but the Characteristic itself can be totally ignored in the sketch.

The `Program Mode` Characteristic is also needed.  Without it, the Home App shows "Updating..." as the status on the Tile.  Setting it to 0 seems to works fine and allows the Home App to toggle between "Off" and "Running" depending on whether you have any Valves open.

The `Name` Characteristics for both the Irrigation Service and Valve Services are completely ignored by the Home App.  This seems to be a trend since iOS 14 with Services that used Linked Services  The default name of the Irrigation Service is instead derived from the name of the device itself (as set by the `homeSpan.begin()` method).  However, the default name of each Valve *can* be set by using the `Configured Name` Characteristic instead.  This also has the nice feature of passing back name changes you make in the Home App to the device itself (if you change the name of a Valve in the Home App you will see this reflected in the diagnostic output of the sketch below).

Finally, the timers shown in the Home App Valves are nothing but countdown displays.  They provide no functionality - the sketch needs to set the timer to the desired duration using the `Remaining Duration` Characteristic when the valve is first open (i.e. Active), and *must* also set the `Remaining Duration` Characteristic back to 0 when the valve is closed.

The sketch below shows how all of this fits together.  You'll note how a Valve automatically resets to closed after the timer expires.  Also, is you manually close a valve and then re-open, the timer resets.

```C+
  ////////////////////////////////////////////////////////
  //                                                    //
  //    HomeSpan Reference SPRINKLERS Sketch:           //
  //                                                    //
  //    * IRRIGATION Service                            //
  //    * Multiple linked VALVE Services                //
  //                                                    //  
  ////////////////////////////////////////////////////////

 
#include "HomeSpan.h" 

struct Head : Service::Valve {

  SpanCharacteristic *active=new Characteristic::Active(0);
  SpanCharacteristic *inUse=new Characteristic::InUse(0);
  SpanCharacteristic *enabled = new Characteristic::IsConfigured(1);
  SpanCharacteristic *setDuration = new Characteristic::SetDuration(30);
  SpanCharacteristic *remainingDuration = new Characteristic::RemainingDuration(0);
  SpanCharacteristic *name;

  Head(const char *headName) : Service::Valve() {
    new Characteristic::ValveType(1);
    name=new Characteristic::ConfiguredName(headName);
    enabled->perms|=PW;
  }

  boolean update() override {
    
    if(enabled->updated()){
      if(enabled->getNewVal()){
        Serial.printf("Head '%s' enabled\n",name->getString());
      } else {
        Serial.printf("Head '%s' disabled\n",name->getString());          
        if(active->getVal()){
          active->setVal(0);
          inUse->setVal(0);
          remainingDuration->setVal(0);
          Serial.printf("Head '%s' valve is closing\n",name->getString());          
        }
      }
    }

    if(active->updated()){
      if(active->getNewVal()){
        Serial.printf("Head '%s' valve is opening\n",name->getString());
        inUse->setVal(1);
        remainingDuration->setVal(setDuration->getVal());
      } else {
        Serial.printf("Head '%s' valve is closing\n",name->getString());
        inUse->setVal(0);
        remainingDuration->setVal(0);
      }
    }
    
    return(true);
  }

  void loop() override {
    if(active->getVal() && (active->timeVal() > setDuration->getVal()*1000)){
      Serial.printf("Head '%s' is closing (%d-second timer is complete)\n",name->getString(),setDuration->getVal());
      active->setVal(0);
      inUse->setVal(0);
      remainingDuration->setVal(0);
    }
  }

};

struct Sprinkler : Service::IrrigationSystem {

  SpanCharacteristic *active=new Characteristic::Active(0);
  SpanCharacteristic *programMode=new Characteristic::ProgramMode(0);
  
};

//////////////////////////////////////

void setup() {

  Serial.begin(115200);
  
  homeSpan.begin(Category::Sprinklers,"HomeSpan Sprinklers");

  new SpanAccessory();                                  

    new Service::AccessoryInformation();
      new Characteristic::Name("Sprinkler System");                   
      new Characteristic::Manufacturer("HomeSpan");             
      new Characteristic::SerialNumber("HSL-123");              
      new Characteristic::Model("HSL Test");                    
      new Characteristic::FirmwareRevision(HOMESPAN_VERSION);   
      new Characteristic::Identify();                           
  
    new Service::HAPProtocolInformation();
      new Characteristic::Version("1.1.0");                     
     
    (new Sprinkler())
      ->addLink(new Head("Head 1"))
      ->addLink(new Head("Head 2"))
      ->addLink(new Head("Head 3"))
      ->addLink(new Head("Head 4"))
      ;

} // end of setup()

//////////////////////////////////////

void loop(){
  
  homeSpan.poll();
  
} // end of loop()

//////////////////////////////////////
```

**Comment by DanielO** [comment]
I didn't bother with the irrigation service - I just created valves and it seemed to work OK. The irrigation service didn't seem to provide any value since you can't configure it (that I can see)

If I look at the valve in detail (ie long press so the switch is full screen) then there is a timer that counts down when it is on.
Unfortunately it becomes inaccurate because when HomeKit fetches it after the timer has started it always reports the initial duration. I could constantly update the remaining duration in loop() but that would be costly in traffic.

I have this diff:
```
diff --git a/src/HomeSpan.h b/src/HomeSpan.h
index 485fea2..fa8270e 100644
--- a/src/HomeSpan.h
+++ b/src/HomeSpan.h
@@ -465,9 +465,8 @@ struct SpanCharacteristic{
   template <class T=int> T getNewVal(){
     return(uvGet<T>(newValue));
   }
-
-  template <typename T> void setVal(T val){

+  template <typename T> void setValIdle(T val){
     if(format==STRING){
       Serial.printf("\n*** WARNING:  Attempt to update Characteristic::%s(\"%s\") with setVal() ignored.  Can't update STRING Characteristics once they are initialized!\n\n",hapName,value.STRING);
       return;
@@ -477,12 +476,16 @@ struct SpanCharacteristic{
       Serial.printf("\n*** WARNING:  Attempt to update Characteristic::%s with setVal(%llg) is out of range [%llg,%llg].  This may cause device to become non-reponsive!\n\n",
       hapName,(double)val,uvGet<double>(minValue),uvGet<double>(maxValue));
     }
-
+
     uvSet(value,val);
     uvSet(newValue,val);
-
+
     updateTime=homeSpan.snapTime;
-
+  } // setValIdle()
+
+  template <typename T> void setVal(T val){
+    setValIdle(val);
+
     SpanBuf sb;                             // create SpanBuf object
     sb.characteristic=this;                 // set characteristic
     sb.status=StatusCode::OK;               // set status
```

And I modified my code to call setValIdle() to update  the remaining duration in its idle loop. It compiles, however I haven't had a chance to test it yet.

I did ponder adding a virtual function in SpanCharacteristic and then sub classing that for RemainingDuration but that class lacks the context to compute the value so I did it this way instead.

**Comment by HomeSpan** [comment]
If you use the Irrigation Service you get the timer display right on the valve for free. You simply set the initial duration and the Home App counts down once inUse is set.  Separately you keep track of the time in the sketch and decide when to turn the valve back off. You should not need to send any network traffic back to the Home App until the sketch closes the valve.  Also, you can also select the duration directly from the Home App, which will be communicated to the device.

**Comment by DanielO** [comment]
I think it will have the same problem where the remaining duration will not be updated.
You can easily test it by turning a valve on, wait 30 seconds, then kill an restart Home.app and view service again.
It (presumably) re-fetches the remaining duration when it starts but the value is now incorrect (ie in my case it resets back to 40 minutes because that is the duration I set on start).

**Comment by HomeSpan** [comment]
Ah - good point.  When the home app fetches all Characteristics it gets the original set duration, not the current time.  This suggests the need for a way to update a characteristic without notification. Should be doable - will explore.

**Comment by DanielO** [comment]
Yeah, I think my patch above does it but as I said I haven't tested it (apart from compilation).
Feel free to change the name as you like :)

**Comment by HomeSpan** [comment]
Thanks.  To keep the library simple I added a second optional argument to setVal().  The argument defaults to `true` (for backwards compatibility), which sends a notification to HomeKit.  Set to `false` and the Characteristic is updated without any notifications.  Changes have been added to the HomeSpan dev branch.

I also uploaded my revised Sprinkler sketch (it uses setVal() with `false` as the second argument that updates the Characteristic once per second) as a part of a new public repo I'm creating with "reference" sketches:  https://github.com/HomeSpan/HomeSpanReferenceSketches/blob/main/ReferenceSprinklers/ReferenceSprinklers.ino

**Comment by HomeSpan** [comment]
Given the changes Apple keeps making to the Home App, and the divergence from the HAP-R2 documentation, I'm a little concerned about Apple's long-term support of the HAP protocol.  I know they have joined the "Matter" initiative with Z-wave and other IOT manufacturers, but Matter has not yet been released.  Until then, HAP is all we have.

**Comment by DanielO** [comment]
Thanks, that looks good - I didn't even know you could do that with C++ 😅

PS don't forget to update the docs.
