### ISSUE TITLE
Is MFi license required inorder to be able to integrate and run in production with HomeSpan?

### ISSUE THREAD

**Issue by thehellmaker** [HomeSpan/HomeSpan#218]

**Comment by HomeSpan** [comment]
Yes, a MFi license is needed.  HomeSpan was developed using Apple's HAP-R2 specs, which Apple provided for home use and experimentation only.  Though I believe the commercial specifications are functionally the same, there is a slight, but critical,  difference in the pairing protocol between HAP-R2 and MFi.  Note that when you pair a HomeSpan device (or any device that is based on HAP-R2, such as Apple's HAP-R2 ADK, Espressif's non-commercial ADK, HomeBridge, etc.) the Home App on your iPhone will flag the device as uncertified and require you to grant it permission to proceed with pairing.  This warning message about the device being uncertified does not appear on commercial devices, presumably because Apply provides the licensee with a custom MFi authorization code that is recognized by the iPhone.
