### ISSUE TITLE
Reset accessory on deletion from Home app

### ISSUE THREAD

**Issue by breitburg** [HomeSpan/HomeSpan#219]
Is it possible to trigger storage reset on accessory removal from Home app?

**Comment by HomeSpan** [comment]
Not at present.  Since a device may be operated by manual controls as well as by Home Kit, there are numerous use cases where one would want to retain the storage settings even after unpairing.  However, for devices operated solely by HomeKit, I can see it would be convenient to remove storage settings.  

There are already a few callbacks in HomeSpan, such as a callback when a WiFi connection is established.  I'll see if I can generalize the concept of a callback under a single homespan method making it easy to add callbacks at various points, such as when pairing is first established, when pairing is removed, if WiFi is lost, etc.

**Comment by HomeSpan** [comment]
HomeSpan version 1.5.0 was just released.  It includes a new method to add a callback when the device is paired/unpaired, and a new method to programmatically delete the values of any Characteristics that are stored in the NVS (which you can invoke when the device is unpaired to achieve the request above).   See the API for details.

**Comment by breitburg** [comment]
Awesome! Thank you very much.
