### ISSUE TITLE
Working with timers to continuously fade LEDs?

### ISSUE THREAD

**Issue by shyd** [HomeSpan/HomeSpan#223]
Hi, currently I am diving into the APIs and fiddling around with LED dimming.

Is there a way to implement some kind of loop() function with certain delays or use hardware timers to change pwm levels continuously?

I am planning to have a LED string fading in sine with a settable maximum level through homekit. The sine freq should be adjustable via a custom characteristic.

Thanks for developing such a great piece of software!

Here is, what I have done so far: https://github.com/shyd/homekit-fireflylight/tree/main/src

**Comment by HomeSpan** [comment]
The HomeSpan PWM class does not include an automatic fading mechanism but the underlying ESP32 hardware peripheral upon which the PWM class is based does contain such functionality.  To use you would need to implement your own LED logic using the native [ESP32 LEDC methods](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/peripherals/ledc.html).  However, the ESP32 library can be quite finicky since you need to keep track of which PWM channels you are using (this is why I created the HomeSpan PWM class - it abstracts away all the logic needed to keep track of the channels).

As an alternative, you can try programming the fading logic directly into the HomeSpan loop() method for the LightBulb service.  For example, you can keep track of when the light is turned on/off with the Home App, but instead of actually turning on/off the light, you can simply set flags that will be read in the Service loop() and slowly fade in/out the light.  [See Example 12](https://github.com/HomeSpan/HomeSpan/blob/master/docs/Tutorials.md#example-12---serviceloops) for details on how Service loops() work in HomeSpan.

Above you mentioned the use of Custom Characteristics.  Note that although you can create a Custom Characteristic in HomeSpan, you still need an App to make any use of it.  The Home App fully ignores any Characteristic that is not defined in HAP-R2, so it won't do anything with a Custom Characteristic.  The Eve for HomeKit App (available for free in iPhone App store) is designed to work with standard HomeKit Accessories as well as Eve Accessories that utilize Custom Characteristics.   In addition, the Eve App seems to be programmed to display any Characteristic it does not recognize in a generic fashion (such as providing a slider for setting uint8_t characteristics from 0-255).  This may be of use if you want to provide some additional HomeSpan controls beyond what's available in the iPhone Home App.

**Comment by shyd** [comment]
> The HomeSpan PWM class does not include an automatic fading mechanism but the underlying ESP32 hardware peripheral upon which the PWM class is based does contain such functionality.  To use you would need to implement your own LED logic using the native [ESP32 LEDC methods](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/peripherals/ledc.html).  However, the ESP32 library can be quite finicky since you need to keep track of which PWM channels you are using (this is why I created the HomeSpan PWM class - it abstracts away all the logic needed to keep track of the channels).
> 

This is exactly what I though on digging into. I'll see what I can do. Maybe I can come up with a solid solution I even can submit to your project.

> 
> 
> [See Example 12](https://github.com/HomeSpan/HomeSpan/blob/master/docs/Tutorials.md#example-12---serviceloops) for details on how Service loops() work in HomeSpan.
> 

Do loop() for all kinds of HomeSpan devices?

> 
> 
> Above you mentioned the use of Custom Characteristics.  Note that although you can create a Custom Characteristic in HomeSpan, you still need an App to make any use of it.

Thanks for pointing out. I know, I use Eve and Home+ to read/write these Characteristics.

Lets see how far I can get with this in next couple of weeks in my spare time.

Happy new year!
