### ISSUE TITLE
additional service and characteristics 

### ISSUE THREAD

**Issue by Pythonaire** [HomeSpan/HomeSpan#268]
I'm not really familiar with C++, more python ;-)
I use a service:
```
"AtmosphericPressureSensor": {
    "OptionalCharacteristics": [
     "Name"
    ],
   "RequiredCharacteristics": [
   "AtmosphericPressure"
   ],
   "UUID": "E863F00A-079E-48FF-8F27-9C2605A29F52"
   }
```

with characteristics:
```
"AtmosphericPressure": {
      "Format": "float",
      "Permissions": [
         "pr",
         "ev"
      ],
      "UUID": "E863F10F-079E-48FF-8F27-9C2605A29F52",
      "unit": "hPa",
      "maxValue": 1200.0,
      "minValue": 700.0,
      "minStep": 0.1
   }
```

I saw the chance to add custom characteristics, but not services and how can i set the longer/non apple UUID String.

Thx for advice

**Comment by danilkorotkov** [comment]
https://github.com/danilkorotkov/GY-21P-HomeKit

**Comment by HomeSpan** [comment]
Thanks for asking this question - I had wanted to test out the ability to create a custom service but did not have a good custom UUID to use.  The example you gave (which I assume is for an Eve sensor) makes a good test case.

As you noted, HomeSpan has a macro that allows you to create a custom characteristic, but no macro for a custom service.  I'll probably create a macro in a future release, but even without one, adding a custom service is nevertheless quite easy.

Instead of implementing a service based on a built-in HomeSpan class, such as *Service::TemperatureSensor*, you instead create a derived service based on HomeSpan's "parent" class, SpanService().  The constructor for SpanService() takes 2 arguments:  A UUID and a Name, which is all that is needed to create a custom Service.

Here is how this looks in practice:

```C++
// First you need to create the custom Characteristic needed by this service using the CUSTOM_CHAR macro

CUSTOM_CHAR(AtmosphericPressure, E863F10F-079E-48FF-8F27-9C2605A29F52, PR+EV, FLOAT, 1013, 700, 1200, false);

// Next implement the custom Service by creating a derived class from SpanService().  The only difference between this and a
// normal HomeSpan service is that on the constructor line below, you will specify the custom UUID and provide a name

struct AtmosphericPressureSensor : SpanService {     // A standalone Air Pressure Sensor

  SpanCharacteristic *atmosphericPressure;           // Eve Air Pressure with range 700-1200 hPa (millibars), where 1013=1 atm
  
  AtmosphericPressureSensor() : SpanService{"E863F00A-079E-48FF-8F27-9C2605A29F52","AtmosphericPressureSensor"} {       // constructor() method that defines the UUID and provided a name
    
    atmosphericPressure=new Characteristic::AtmosphericPressure();
    
    Serial.print("Configuring Air Pressure Sensor");   // initialization message
    Serial.print("\n");

  } // end constructor

  void loop(){

    if(atmosphericPressure->timeVal()>5000)                     // here we simulate an actual sensor by generating a random pressure reading every 5 seconds
      atmosphericPressure->setVal((double)random(900,1100));
       
  } // loop

};

// You can now invoke this custom service as you would any other service (e.g. new AtmosphericPressureSensor()) in the main setup() portion of your sketch
```

I tested this with the Eve for HomeKit App and it worked exactly as expected.  One thing to note is that similar to custom characteristics, custom services are not supported by Apple's native Home App.  However, whereas Apple's Home App will simply ignore any custom characteristics it finds, it warns about using a custom service and creates a tile that simply says "Not Unsupported."  This fortunately doesn't appear to create any problems for the Home App.

Note that you do not need to specify the units or the minStep.  This is because you are using a UUID that is recognized by the Eve App, which has all of this information already.  The only reason the minVal and maxVal are specified in the CUSTOM_CHAR macro is so that HomeSpan itself can do some range checking for you and provide warning messages if you set an out-of-range value.

Final note:  You do not need to specify which characteristics are optional or required for a custom service.   If you added a standard HomeSpan characteristic (like Characteristic::Name)  to the code above, it would work fine though HomeSpan will warn you upon start-up that you are using a Characteristic that is not known to be required or optional for the service.   There are two other helper macros you can use to inform HomeSpan of which Characteristics are optional and which are required:  OPT() and REQ().  For example, adding `OPT(Name);` in the constructor section above will let HomeSpan know that Characteristic::Name() is optional for this service (and thus not to warn you if you use it).   I would not bother adding these given the simplicity if the service itself.
