### ISSUE TITLE
Make it possible to preset client SSID and password

### ISSUE THREAD

**Issue by flashspys** [HomeSpan/HomeSpan#27]
As far as I can see it is not possible to set the SSID and password (for the wifi where the device will finally work in) via code. Like the `homeSpan.setApSSID(ssid)` method I propose `homeSpan.setSSID(ssid)` as well as for the passwords.

**Comment by HomeSpan** [comment]
I left those out by design.  You can set the network SSID/PWD in the interface using the "W" command (which saves it in NVS storage) but you can't set it directly in the code.  I know it's common practice, and the Arduino IDE even supports a "secrets" tab.  But in an open-source environment where everybody shares their code, and people send me sketches to debug, I wanted to avoid the issue of someone accidentally posting their password in a sketch for everyone to see.

Same thing with the Setup Code.  In most HomeKit libraries this is included in the sketch.  In HomeSpan this is only set via the interface, and a hashed version, rather than the actual setup code, is saved in NVS storage (per HAP requirements).

**Comment by aaaidan** [comment]
I support the current design, and reasons for it. 

Even so, it would be interesting to hear more from OP about what they'd hoped to use it for, and whether existing methods (CLI, Homespan Wifi Access point) are insufficient for them. Could you say more, @flashspys?

In my own experience with HomeSpan, this was an early stumbling block for me. The use of the CLI to setup wifi is a critical step, and I don't think its importance is currently mirrored in the docs.

**Comment by HomeSpan** [comment]
I created a new [FAQ](https://github.com/HomeSpan/HomeSpan/blob/master/docs/FAQ.md) page and added this as the first question.
