### ISSUE TITLE
[D][WiFiClient.cpp:452] connected(): Disconnected: RES: 0, ERR: 128 -- switch to async TCP?

### ISSUE THREAD

**Issue by terhorst** [HomeSpan/HomeSpan#31]
Hi,

First, thanks for creating such a nice and well documented library! It's been a real pleasure to work with.

I'm using an ESP32 Pico and have noticed some problems when a lot of network traffic gets generated. The logs full up with the following error message:
```
[D][WiFiClient.cpp:452] connected(): Disconnected: RES: 0, ERR: 128
```
Whenever this happens, the device goes into a "Not responding" state in HomeKit, and stays that way for a few minutes.

I don't think this is due to a bug in your code, but rather is a known issue with ESP32 (cf. espressif/arduino-esp32#1921). The root cause of the bug is unknown but one suggested resolution is to switch to asynchronous TCP. I was wondering if this is something you would consider implementing? Async seems like a much better model for servicing HomeKit requests in general.

I think it would be fairly easy do to using me-no-dev/ESPAsyncWebServer, basically amounting to a few straightforward changes in Network.cpp. Normally I'd implement this myself and submit a PR, but my time to work on side projects is unfortunately very limited right now. I figured I'd throw it out in case you (or anyone else) has the time. 

Thanks again!

**Comment by HomeSpan** [comment]
Thanks for the feedback on this issue, though I haven't noticed this particular problem with WiFi disconnects in my own setup.

If you type the 's' command into the CLI, how many active connections does it show?  If it shows all 8 are active (slots 0-7), but you have more than 8 Controllers trying to connect to HomeSpan, HomeSpan will replace an existing connection slot (chosen at random) upon each new request from an unconnected Controller.  Since this can cause a lot of thrashing, you can try raising the number of max simultaneous connections to 16, using `homeSpan.setMaxConnections(16);`

Please let me know if that helps address the issue.

I checked out the ESPAsyncWebServer you recommended, but based on the description I don't think this will work for HomeKit.  As opposed to a traditional server, HAP Servers are funneling multiple requests to a single instance of a light or other physical device.  To ensure a device does not wind up in an impossible or unknown state, Controller requests need to be handled serially.  In contrast, the ESPAsync method seems to require non-blocking processes that handles asynchronous requests as they arrive.  For a web server this may be fine, but I'm not sure how to translate this for HomeKit requests.

One thing to note is that even though HAP/HomeKit uses HTTP, it doesn't follow a traditional client/server route.  HAP keeps connections open indefinitely, and expects to be able to send or receive data at any time.  For example, during initial pairing there are multiple rounds of back-and-forth between the Home App and HomeSpan, but only one, very state-oriented connection, where both the Home App and HomeSpan need to keep track of each step in the pairing process.  There is also special logic that resets certain state variables if other connections are attempted during the pairing process.

Once connected, other Controllers can then join, and each also keeps its connection open after an initial request for a download of the HomeSpan Accessory database.  Keeping connections open is how HAP enables event notification.

This is because after downloading the Accessory database from HomeSpan, a Controller can request to be informed of a certain events of interest, such as updates to a temp sensor or an update whenever a light is turned on or off.   HomeSpan keeps track of every one of these requests to be notified, and whenever the state of something changes, it determines which Controllers requested an update, and ten sends them an update through a custom HTTP response.  HomeSpan does not (can not) initiate a connection with a Controller - HAP connections are all one way (from Controller to HomeSpan).  As long as the Controller keeps its connection open to HomeSpan, it will be informed of any events it had previously "subscribed" to.

Connections are typically open for hours if not days.  If a Controller goes off line, it reconnects whenever needed.  But HomeSpan can not reach to an unconnected Controller.  However, as noted above, HomeSpan can force a disconnect.  This occurs when all its "connection slots" have filled up, and it receives a yet another request to connect.

The details of how this works are documented in the HAP.cpp file.  Note that the Network.cpp code is unrelated to HAP and HomeKit.  That code is a standalone (temporary) web server supporting HomeSpan's Access Point used for configuring WiFi Credentials.
