### ISSUE TITLE
HSV to RGB Function for Anode RGB LEDs?

### ISSUE THREAD

**Issue by vicc** [HomeSpan/HomeSpan#313]
Trying out the RBG tutorial with an anode RGB LED and getting inverted results. Turning off the LED in HomeKit turns it on and vice versa. Also, the RGB values are all wonky.

When I look at the Logger I see the following:
```
Updating RGB LED: Pins=(32,22,23): Power=true, H=119->353, S=88->97, V=100  RGB=(100,2,14)
```

I was expecting (255, 0, 0). Below is a picture of my anode LED setup, as well as HomeKit app setting 

![Image 3](https://user-images.githubusercontent.com/1724674/167199703-8c08bfd9-7b7d-44c3-9558-1bd866df8d1e.png)

**Comment by HomeSpan** [comment]
Have you made any modification at all to the code?   What version of the Arduino-ESP32 IDF are you using (2.0.2?).  I've just loaded this example on my kit and it is operating as expected.

**Comment by vicc** [comment]
Turns out I was on 1.8.4, so I went ahead and updated to 2.0.0, and currently running the Homespan sketch example unmodified. Here's what I'm seeing:

I have a common anode RGB LED (only lights up when the longest end of the leg is connected to the 3.3v pin instead of ground). Everything seems to be inverted (turning off the bulb in HomeKit turns the LED on, etc).

Looks like it's spitting out the inverse RGB values as well. For example, when I tap "red" it spits out the following values:

``` c++
Updating RGB LED: Pins=(32,22,23): Power=true, H=119->353, S=88->97, V=100  RGB=(100,2,14)
Updating aid=4 iid=6 (okay)
Updating aid=4 iid=7 (okay)
```

The hue values are correct (I plugged them into Google's color picker to verify), however, the RGB values are not. I'm seeing `100, 2, 14` instead of `255, 8, 37`. Below are some screenshots of the results.

![Image 5](https://user-images.githubusercontent.com/1724674/167230387-5c56ae0c-88cb-4fa4-bebf-54b01047d850.png)

![Image 4](https://user-images.githubusercontent.com/1724674/167230333-9d3aec40-0e0f-4150-9f5a-a4c8a2ba8b50.png)

![Image 6](https://user-images.githubusercontent.com/1724674/167230421-076cce5c-d67b-46f1-a0e3-1e7535256a94.png)

**Comment by vicc** [comment]
I did notice that there is an inconsistency in the comments. For example in the `RGB-LED.ino` file, Line 73 mentions it is for anode LEDs:
``` c++
new DEV_RgbLED(32,22,23); // Create an RGB LED attached to pins 32,22,23 (for R, G, and B LED anodes)
```

However in the `"DEV_LED.h"` file, Line 97 references a cathode LED:

``` c++
struct DEV_RgbLED : Service::LightBulb { // RGB LED (Command Cathode)
```

**Comment by HomeSpan** [comment]
The sketch is designed for a Common Cathode LED, as you noted above.  In this type of LED there is one (common) Cathode and three Anodes - one for the R LED, one for the G LED, and one for the B LED, as per Line 73.

The sketch would need to be modified to work with a Common Anode LED (which is what you have).  The PWM module may also need to be modified to allow for current to sync instead of source, but it may work as is.

The RGB numbers are correct.  As noted in the comments, the RGB numbers returned from the HSV conversion are in the range of 0-1.  The PWM code uses numbers from 0-100, hence the multiplication by 100.  To re-scale the numbers where 255 is the max, you can multiply the values by 2.5 (numbers may not match exactly since decimals are not shown in the output).

**Comment by HomeSpan** [comment]
Here is a good link the describes the differences and how to transform values between the two types of LEDs:

https://makeabilitylab.github.io/physcomp/arduino/rgb-led.html

**Comment by vicc** [comment]
Ah I see. Might be worth adding support for both types of LEDs, but given the popularity of cathode LEDs it's probs not worth it.
