### ISSUE TITLE
Adding and removing Accessories on the fly

### ISSUE THREAD

**Issue by batonPiotr** [HomeSpan/HomeSpan#325]
I configured my ESP32 with HomeSpan as Bridge. It works well when I configure all accessories and services upfront, but whenever I add or remove any device after I pair it with my HomeKit, there are no updates on the iPhone. Devices don't respond anymore and new won't be added.

I remove accessories with following code:

```
    if(m_hsSpanAccessory != NULL)
    {
        for(int i = 0; i < homeSpan.Accessories.size(); i++)
        {
            if(homeSpan.Accessories[i] == m_hsSpanAccessory.get())
            {
                homeSpan.Accessories.erase(homeSpan.Accessories.begin() + i);
            }
        }
    }

    m_hsSpanAccessory.reset(nullptr);
```

`m_hsSpanAccessory` is a `std::unique_ptr` so I reset it to remove any existing pointers.

Is there any way how I could do it without resetting the device and re-pairing it over and over again?

**Comment by HomeSpan** [comment]
In the current version all Accessories need to be added before the first  `homeSpan.poll()` is run.  However, I have just finished adding new functionality to allow the dynamic creation (and deletion) of Accessories at any time without needing to reboot the device.  This will be published shortly in the next production release, but if you'd like you can test it out now on the "dev" branch.  Note the documentation for the dev branch is also updated, so you'll be able to review the docs for the new `homeSpan.updateDatabase()` and `homeSpan.deleteAccessory()` methods, as well as new Example Tutorial 20, that demonstrates how to use these methods (including a few other advanced HomeSpan techniques).

**Comment by batonPiotr** [comment]
It's just perfect, thank you for your quick response. I'll test it immediately and let you know if I find any issues.

**Comment by batonPiotr** [comment]
After some testing I could get it to work and it has worked indeed but there were some problems with stability. I cannot say if it was fault of my code or the library though. I'll debug it more closely.

I've added some minor pull requests to make it easier to handle the new features.

**Comment by HomeSpan** [comment]
A few things to note:

* HomeKit requires that for any given device the AID numbers of each Accessory remain unique AND consistent.  This means if you define and Accessory with AID=3 to contain a LightBulb and Fan Service, then AID=3 (if defined) must always contain those two Services.  It's fine to delete AID=3 dynamically, or eliminate it entirely from the setup, but AID=3 cannot be used again (on the same device) unless it defined the same way.  In other words, if you dynamically delete an Accessory with AID=3 and then want to add an Accessory with a different set of Services, HomeKit will misbehave if you re-use AID=3.  You should only re-use AID=3 if you are planning on adding back the same exact set of Services (defined in the same order so the IIDs are also the same).

* Originally I had exposed the destructor for an Accessory so that you can simply say `delete acc1` to remove an Accessory dynamically, but I realized that users who wanted to perform dynamic add/deletes would always need to manage the AIDs to make sure they don't get re-used.  To enforce this, I made the destructor a private member of Accessory and created `homeSpan.deleteAccessory(aid)` instead.

* If you don't specify an AID when creating an Accessory, HomeSpan automatically creates one by incrementing the AID of the last Accessory defined.  This is fine under most circumstances if you are not going to dynamically add/delete Accessories.

* While developing a static HomeSpan sketch (one that does not make dynamic changes), it is not uncommon to nevertheless make a lot of modifications to Accessories in the setup() routine every time you recompile.  Because HomeKit itself retains knowledge of AIDs once a device is paired, the changes you make if you alter your sketch can  also lead to HomeKit confusion.  Sometimes the Home App sorts itself out, other times it does not.  To fix this issue you need to unpair the device and then type 'H' into the CLI.  This causes HomeSpan to generate a new device ID so that the next time you pair the device, the Home App will think it is new and not confuse it with any other AIDs it retained from the previous device ID.  This is usually not an issue when developing HomeSpan sketches, but does occur occasionally. 

* The new Example 20 tutorial (thanks for catching the typo in my link!) also demonstrates the use of the `homeSpan.autoPoll()`.  This works fine in the sketch as constructing because the dynamic add/delete code is embedded in user-defined CLI commands, which themselves are called from HomeSpan's polling function.  This prevents any race multi-thread conditions.  However, depending on how you constructed your code, I recommend not using `homeSpan.autoPoll()` (as introduced in Example 20) but rather include `homeSpan.poll()` in the Arduino `loop()` function as is more typical.  This will ensure that you won't add or delete an Accessory while HomeSpan is in the middle of polling, which can lead HomeSpan to try to access an Accessory that you deleted in a parallel process (and result in a core dump).

* I'm currently working on a method to allow users to pause autoPolling so that they can safely add/delete an Accessory in a parallel thread and avoid such multi-thread race conditions.  As noted above, none of this is an issue if you don't use the new "experimental" autoPolling feature.

**Comment by batonPiotr** [comment]
Thanks for the insights, it will be surely helpful. Especially that part about the handling of AIDs by the HomeKit.

**Comment by HomeSpan** [comment]
FYI - HomeSpan version 1.6.0 (just released) now includes all the dev functionality described above, with the exception of methods to "pause" auto polling noted in the last bullet point.  See the updated [API Reference](https://github.com/HomeSpan/HomeSpan/blob/master/docs/Reference.md) and new [Example 20 - AdvancedTechniques](https://github.com/HomeSpan/HomeSpan/tree/master/examples/20-AdvancedTechniques) for full details.  See also the new [Other Examples → Programmable Hub](https://github.com/HomeSpan/HomeSpan/tree/master/Other%20Examples/ProgrammableHub) sketch, which includes a web interface that allows the user to  dynamically add, delete, and configure LightBulb Accessories, as well as update HomeKit, without the need to reboot the device.
