### ISSUE TITLE
Read of the button state from the mcp expander.

### ISSUE THREAD

**Issue by glock4101** [HomeSpan/HomeSpan#345]
Read of the button state from the mcp expander.
How can I use the buttons connected by the mcp expander.
currently I have it done like this:
  new SpanButton (mcp.digitalRead (BtnPin), 1000, 10, 500);

and its not working.

**Comment by HomeSpan** [comment]
SpanButton is designed to read a physical ESP32 pin connected to ground through a button.  It debounces the signal, and converts the duration of high->low transitions into long/short/double presses.  In contrast, the MCP is an interface into virtual pins that don't exist on the ESP32, so SpanButton won't work.  In the above code the first argument is supposed to be an ESP32 pin number but you are passing it a 0 or 1 (depending on the state of your MCP pin at the time this line is executed), which means SpanButton is going to process signals from either pin 0 or pin 1 on the ESP32, which I don't think is what you are trying to do.

Instead of using SpanButton, you'll need to call MCP directly to read the status of the button.  You can do this inside the `loop()` method of your service, and trigger any actions based on whatever the status of mcp.digitalRead() is at that time.  You would not use the `button()` method since that is only called by SpanButton.

I'm not familiar it the details of mcp.digitalRead() so I don't know if it automatically debounces switches.  If so, then mcp.digitalRead() will return a clean 0 or 1.  If not, you'll need to either add some debounce hardware or some debounce logic in the `loop()` method to filter out noise in the signal generated as the button is pressed or released.

If the MCP library includes routines to determine short/long/double presses you can use them as well.  If not, you'll have to create your own logic (also in the `loop()` method of your service) to do so.

**Comment by HomeSpan** [comment]
HomeSpan version 1.6.0 (just released) now includes the ability to seamlessly add pushbuttons attached to a pin expander.  Complete details can be found in the the latest version of [SpanButton()](https://github.com/HomeSpan/HomeSpan/blob/master/docs/Reference.md#spanbuttonint-pin-uint16_t-longtime-uint16_t-singletime-uint16_t-doubletime-boolean-triggertypeint) in the API documentation, with additional tutorial instructions  describing how to create your own *triggerType* function added to the end of [Example 15 - RealPushButtons](https://github.com/HomeSpan/HomeSpan/tree/master/examples/15-RealPushButtons).  Thanks for raising this issue/request.
