### ISSUE TITLE
Thermostat target temperature (and what is Thermostat vs HeaterCooler)

### ISSUE THREAD

**Issue by iKrushYou** [HomeSpan/HomeSpan#364]
Hey,

Currently building a controller for my mini-split aircon and I've run into some issues, perhaps you might have solved these before

1. I have a Thermostat set up and I am seeing the targetTemperature reflected in the Home app. I have manually set the target temp to 70 and it's reading "Cooling to 70". However.. I can't seem to figure out how to get the control for target temp available in the Home app. Am I missing something? 

```
struct ThermostatController : Service::Thermostat
{

  SpanCharacteristic *active;
  SpanCharacteristic *currentTemperature;
  SpanCharacteristic *targetTemperature;
  SpanCharacteristic *currentHeatingCoolingState;
  SpanCharacteristic *targetHeatingCoolingState;
  SpanCharacteristic *coolingThresholdTemperature;
  SpanCharacteristic *heatingThresholdTemperature;
  // SpanCharacteristic *rotationSpeed;
  boolean updating = false;

  ThermostatController() : Service::Thermostat()
  {
    // 0 - off
    // 1 - on
    this->active = new Characteristic::Active();

    // value in centigrade
    this->currentTemperature = new Characteristic::CurrentTemperature(10.0);
    this->targetTemperature = new Characteristic::TargetTemperature(10.0);

    // 0 - inactive
    // 1 - idle
    // 2 - heating
    // 3 - cooling
    this->currentHeatingCoolingState = new Characteristic::CurrentHeatingCoolingState();
    this->targetHeatingCoolingState = new Characteristic::TargetHeatingCoolingState();

    this->coolingThresholdTemperature = new Characteristic::CoolingThresholdTemperature();
    this->heatingThresholdTemperature = new Characteristic::HeatingThresholdTemperature();

    // value between 0 and 100
    // this->rotationSpeed = new Characteristic::RotationSpeed();

  }
```

2. In this project I have tried both HeaterCooler and Thermostat.. and I'm having a hard time figuring out what the difference. The only difference I've found is that Thermostat has a `targetTemperature` (not sure why HeaterCooler doesn't) but.. HeaterCooler has a fan speed...

Any advice appreciated

**Comment by HomeSpan** [comment]
I think you are mixing Thermostat and HeaterCooler Characteristics.  In a Thermostat Service, `Characteristic::TemperatureDisplayUnits()` is *required* - without it the Home App does not display the temperature control.  The CLI should have reported a warning about this in the Serial Monitor when the device first boots.  Also, `Characteristic::Active()` is not applicable for `Service::Thermostat()`.  HomeSpan will warn you about this as well, though it does no harm since the Home App will simply ignore a Characteristic that is not applicable for a given Service.

The reverse is true for a HeaterCooler:  `Characteristic::Active()` is *required*.  Also, `Characteristic::TemperatureDisplayUnits()` is optional.

The differences between Thermostat and HeaterCooler Services are somewhat historical.  I think HeaterCooler may have come first and then Thermostats were added later as Nest and Ecobee starting producing "smart" thermos.  Also, HeaterCooler is designed more for a standalone floor or wall unit that you can simply turn on (hence the Active Characteristic) whereas Thermostat reflects a separate device that controls a furnace-AC unit.
