### ISSUE TITLE
Next generation Matter 

### ISSUE THREAD

**Issue by jonsmirl** [HomeSpan/HomeSpan#375]
If you are interested in building a next generation Matter version of this, some good examples:
https://github.com/espressif/esp-matter/tree/main/examples

The Zigbee and BLE bridges have the ability to dynamically add/remove devices.
These are just examples, not nearly as full featured as HomeSpan.

Matter support mostly works in IOS 16.1
https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/darwin.md

**Comment by HomeSpan** [comment]
Thanks for the links.  If Matter takes off, as I hope it will, I'm anticipating there will be a lot of libraries, both commercial and open-source, that will make it easy to connect a wide variety of devices to HomeKit/Alexa/Google.  Provided that the protocol continues to remain fully open, AND it gets updated, Matter would likely displace the HomeKit protocol itself at some point in the future.  The biggest problem I have with HomeKit is that Apple does not really support non-commercial use.  The HAP docs were incomplete when first published (there are critical steps to pairing that are missing, I assume by accident), and have not been updated since 2019, even though HomeKit has evolved a lot since then.

**Comment by jonsmirl** [comment]
Matter explicitly allows you to use non-certified devices. When you add them to the network you get a prompt indicating non-certified allowing you to add them anyway.  This works in those OS beta links.

Matter has a lot of Homekit inside of it. Apple donated Homekit to the Matter effort and the Apple Homekit developers are working on Matter.  https://developer.apple.com/videos/play/wwdc2021/10298/ last half of video

The Matter spec is still behind a paywall, but it is just Zigbee Cluster Library warmed over. Google for Zigbee Cluster Library and you will find full specs.  Matter == ZCL + Homekit security.  Everything will be released by the end of the year, but you don't really have to have the spec right now, esp-matter has enough to get you going.  esp-matter has a large library inside of it implementing the spec so that you don't have to.

**Comment by HomeSpan** [comment]
Thanks - this is really helpful.

**Comment by ivishaltejwani** [comment]
any update on this ? since Matter 1.1 is released

**Comment by HomeSpan** [comment]
No plans to add Matter to HomeSpan at present.  I assume the use case would be for HomeSpan to work with Google and other non-HomeKit ecosystems?

**Comment by ivishaltejwani** [comment]
yes , and ble support for adding devices. amazing work on the library btw any idea if using homespan we can get devices to  certify?

**Comment by HomeSpan** [comment]
To certify requires an MFi license from Apple, and they need to test the device before certifying.  I believe that means that those using the library would also need to each have their own MFi licenses and perhaps submit their devices to Apple for testing.  There's unfortunately not a lot of public info about the MFi program out there.

**Comment by ivishaltejwani** [comment]
Cool , would love to see a matter library one day , its going to be a huge hit considering how bad the esp-idf and programming with it is for people who have majorly worked on Arduino ide. I would love to help in anyway possible if you plan on working on it

**Comment by jonsmirl** [comment]
Matter is run by the CSA, not Apple. There are 'test' ID which can be used for free.
https://csa-iot.org/all-solutions/matter/
