### ISSUE TITLE
Adaptive Lightning Support

### ISSUE THREAD

**Issue by mLihs** [HomeSpan/HomeSpan#401]
Hi,
I wonder if it would be possible to implement the Adaptive Lightning 

https://github.com/homebridge/HAP-NodeJS/blob/master/src/lib/controller/AdaptiveLightingController.ts

thanks in advance

**Comment by HomeSpan** [comment]
I'm not sure - what is Adaptive Lighting?  What is the functionality you are looking to produce?

**Comment by mLihs** [comment]
It’s a function where HomeKit controls the light temperature of lightbulbs throughout the day based on the “sunlight” and geographical position a like Night Shift  and without user interaction. 

If a light supports the adaptive light function a new icon appears within in the color settings and users can turn it on.

**Comment by HomeSpan** [comment]
Creating an adaptive light that is controlled solely by HomeSpan would be relatively straightforward assuming it appeared as a normal light in the Home App.  All the logic for changing the light based on time of day would reside in HomeSpan and not be accessible in the Home App.  

Getting the "adaptive" part into the Home App would be more difficult since there do not appear to be any specs listing the Service UUIDs and Characteristic UUIDs that are needed.  HomeBridge appears to have reverse-engineered this from somewhere, but Apple does not seem to have publicly-available specs on this.   If you knew what combinations of Services and Characteristics were needed, it's easy to add them into HomeSpan (which supports custom UUIDs) with one caveat:  HomeSpan does not include support for the TLV datatype (it includes all other datatypes such as int, uint16, string, float, etc.).  If Adaptive Lighting requires the TLV datatype, it would not be possible to add this to HomeSpan unless I added TLV support.

**Comment by nbelles** [comment]
Made a comment here: https://github.com/HomeSpan/HomeSpan/issues/748#issuecomment-4849208206 describing changes I made in PR: https://github.com/HomeSpan/HomeSpan/pull/1163 showing how to add Adaptive Lighting
