### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by s1345020674** [HomeSpan/HomeSpan#419]
# The example of homespan compiled with arduino failed
## arduinoIDE version
ArduinoIDE v2.0.0
## espressif/arduino-esp32 version
2.0.5
## esp32 board 
ESP32_DEV_Module
## Homespan version
homespan 1.6.0
## There was no problem building the example for arduino-esp32
~~~
Using library WiFi at version 2.0.0 in folder: D:\Arduino\hardware\espressif\esp32\libraries\WiFi 
"D:\\Arduino\\hardware\\espressif\\esp32/tools/xtensa-esp32-elf/bin/xtensa-esp32-elf-size" -A "C:\\Users\\bingbing\\arduino-sketch-94AAF0FB4D47EE2DF845A35CBAD2E395/WiFiAccessPoint.ino.elf"
Sketch uses 691189 bytes (52%) of program storage space. Maximum is 1310720 bytes.
Global variables use 37488 bytes (11%) of dynamic memory, leaving 290192 bytes for local variables. Maximum is 327680 bytes. 
~~~
## Build error for Homespan examples
~~~
Using board 'esp32' from platform in folder: D:\Arduino\hardware\espressif\esp32
Using core 'esp32' from platform in folder: D:\Arduino\hardware\espressif\esp32
ID:\\Arduino\\hardware\\espressif\\esp32/tools/sdk/esp32/qio_qspi/include" -mlongcalls -Wno-frame-address -ffunction-sections -fdata-sections -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-sign-compare -ggdb -Os -freorder-blocks -Wwrite-strings -fstack-protector -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -std=gnu++11 -fexceptions -fno-rtti -c -w -w -x c++ -E -CC -DF_CPU=240000000L -DARDUINO=10607 -DARDUINO_ESP32_DEV -DARDUINO_ARCH_ESP32 "-DARDUINO_BOARD=\"ESP32_DEV\"" "-DARDUINO_VARIANT=\"esp32\"" -DARDUINO_PARTITION_default -DESP32 -DCORE_DEBUG_LEVEL=0 -DARDUINO_RUNNING_CORE=1 -DARDUINO_EVENT_RUNNING_CORE=1 -DARDUINO_USB_CDC_ON_BOOT=0 "@C:\\Users\\bingbing\\arduino-sketch-D6410C67167363EC6486A7E341C66B61/build_opt.h" "-ID:\\Arduino\\hardware\\espressif\\esp32\\cores\\esp32" "-ID:\\Arduino\\hardware\\espressif\\esp32\\variants\\esp32" "-Id:\\Arduino\\libraries\\HomeSpan\\src" "-ID:\\Arduino\\hardware\\espressif\\esp32\\libraries\\ArduinoOTA\\src" "-ID:\\Arduino\\hardware\\espressif\\esp32\\libraries\\WiFi\\src" "-ID:\\Arduino\\hardware\\espressif\\esp32\\libraries\\Update\\src" "C:\\Users\\bingbing\\arduino-sketch-D6410C67167363EC6486A7E341C66B61\\sketch\\01-SimpleLightBulb.ino.cpp" -o nul
Alternatives for core_version.h: []
ResolveLibrary(core_version.h)
  -> candidates: []
In file included from d:\Arduino\libraries\HomeSpan\src/HomeSpan.h:43,
                 from c:\Windows\Temp\.arduinoIDE-unsaved2022929-31016-2fdpjh.37h\01-SimpleLightBulb\01-SimpleLightBulb.ino:60:
d:\Arduino\libraries\HomeSpan\src/Settings.h:30:10: fatal error: core_version.h: No such file or directory
 #include <core_version.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.

Using library HomeSpan at version 1.6.0 in folder: D:\Arduino\libraries\HomeSpan 
Using library ArduinoOTA at version 2.0.0 in folder: D:\Arduino\hardware\espressif\esp32\libraries\ArduinoOTA 
Using library WiFi at version 2.0.0 in folder: D:\Arduino\hardware\espressif\esp32\libraries\WiFi 
Using library Update at version 2.0.0 in folder: D:\Arduino\hardware\espressif\esp32\libraries\Update 
exit status 1

Compilation error: exit status 1
~~~
## I tried to do that

1. I can't find core_version.h in my disk D:\Arduino\hardware\espressif\esp32\cores\esp32
2. I can't find the core_version.h file in https://github.com/espressif/arduino-esp32/tree/2.0.5/cores/esp32

**Comment by HomeSpan** [comment]
Did you manually install the ESP32-Arduino package or did you use the Arduino IDE board manager?

Note the *core_version.h* file is built into the ESP32-Arduino release files.  For example see the latest 2.0.5 version of the full ESP32-Arduino package:  https://github.com/espressif/arduino-esp32/releases/download/2.0.5/esp32-2.0.5.zip.  For some reason, Espressif adds this file to each release package but does not include it in the branches of the code within GitHub itself (which is why you can't find it in the link above).

If you use the Arduino IDE Board Manager, everything is automatic -- the board manager uses the proper release files and core_version.h will be installed with the full ESP32-Arduino package.  However, if you manually install the ESP32-Arduino package you need to copy the **release** file associated with each version - simply downloading the "source code" from a tagged ESP32-Arduino branch does not provide the core_version.h file.

The reason HomeSpan uses core_version.h is that it is the only reliable source of the version number for any given ESP32-Arduino release.  There is an alternative file, esp_arduino_version.h, that is in the branch of each release but unfortunately Espressif forgot to update the version number in this file and versions 2.0.1 and 2.0.2 both incorrectly show 2.0.0 in this file.

**Comment by s1345020674** [comment]
I successfully builded, thank you.   ：）
