### ISSUE TITLE
Doorbell accessory using the ESP32

### ISSUE THREAD

**Issue by baumph** [HomeSpan/HomeSpan#436]
Hi! I am trying to get my dumb old doorbell integrated into HomeKit using a ESP32. My plan is to connect the ESP32 in between the wires ringing the bell and using the ESP as sort of a sensor wether someone rang the bell or not. 
Now to my question. I have seen in the Service and Characteristics page that a Doorbell service is supported. Can I use one of your example files and modify it that it shows up in the Home App as a doorbell? And is it possible to use the ESP32 to sense wether someone rang the bell or not?

I am sorry in advance, as I am completely new to the ESP and only have experience in programming Raspberry PIs. But I really hope that I can use the ESP32 to make my doorbell smart.

**Comment by HomeSpan** [comment]
Unfortunately Apple seems to have discontinued support of the Doorbell Service.  But since it is specified in HAP-R2, I've left it in  HomeSpan should Apple support it in the future.   

My recommendation would be to setup your doorbell as a Contact Sensor in HomeSpan.  You can then configure the Home App on your iPhone to notify you when the contact sensor is closed (i.e. when the doorbell is pressed).   Here is a snippet of code that you can use as the basis of a sketch for a contact sensor:

```C++

#include "HomeSpan.h" 

//////////////////////////////////////////////////////

struct MySensor : Service::ContactSensor {

  SpanCharacteristic *sensorState;
  
  MySensor() : Service::ContactSensor(){      // constructor
    
    sensorState=new Characteristic::ContactSensorState();    // instantiate contact sensor state
    
  }

  void loop(){

    // Here we simulate a contact sensor toggling from open to close every 10 seconds.
    // You would replace this with logic that, for example, polled an ESP32 pin connected to some sort of real sensor
    
    if(sensorState->timeVal()>10000){                        // check time elapsed since last update and proceed only if greater than 10 seconds (=10,000 milliseconds)
      
      sensorState->setVal(1-sensorState->getVal());          // toggle the state from 0->1 or from 1->0
      
      LOG1("Sensor State = %d\n",sensorState->getVal());     // print new state
    }
    
  } // loop
  
};

//////////////////////////////////////////////////////

void setup() {
  
  Serial.begin(115200);

  homeSpan.begin(Category::Sensors,"HomeSpan Sensors");

  new SpanAccessory();  
    new Service::AccessoryInformation();
      new Characteristic::Identify(); 
      new Characteristic::Name("My Sensor");
    new MySensor();                               // create a contact sensor using structure defined above

} // end of setup()

//////////////////////////////////////

void loop(){
  
  homeSpan.poll();
  
} // end of loop()

//////////////////////////////////////
```

**Comment by baumph** [comment]
Thank you for your reply! Unfortunately the code you posted runs into a compiling error on my side. And could you also change it that it checks for the ESP pins? 
I know I am asking for much, but as said, I don't have a lot of experience in this.

**Comment by HomeSpan** [comment]
The code above should compile in the Arduino IDE without any issues.  Have you correctly configured the Arduino IDE with support for the ESP32?  And have you installed the HomeSpan library?

**Comment by EnricoNapolitan** [comment]
Hi! The @HomeSpan 's solution seems to work, my problem is that I can't turn on the notifications because the Home App says the accessory is not certified. Do you have any solution for this? Thank you
![image](https://user-images.githubusercontent.com/47480416/212467963-aba547ce-48d2-4f48-a981-49aa7e526c3d.png)

**Comment by HomeSpan** [comment]
No, this is hardcoded by Apple.  See the [FAQ](https://github.com/HomeSpan/HomeSpan/blob/master/docs/FAQ.md#can-homespan-be-used-for-commercial-devices) for details.
