### ISSUE TITLE
Status LED stuck in CONNECTING but only when powered from External 5V in; not USB plug

### ISSUE THREAD

**Issue by z3ugma** [HomeSpan/HomeSpan#464]
Hi, I have a very perplexing bug. 

I'm using this Dev Kit: https://www.amazon.com/gp/product/B0718T232Z/ref=ppx_yo_dt_b_asin_title_o01_s01?ie=UTF8&psc=1 

It has a 5V in pin. I have this 5V pin in hooked up to a 5V, 6A power supply. I have tested this power supply with a multimeter and found it to provide an accurate 5.00V. 

I have loaded the example sketch for `ProgrammableHub` https://github.com/HomeSpan/HomeSpan/blob/master/Other%20Examples/ProgrammableHub/ProgrammableHub.ino 

and specified that the StatusLED is pin 2, which is a onboard LED connected to IO pin 2 on this dev kit. 
I further specified that the control button is IO0, an onboard button.

When I power the dev kit using a 1A USB brick, or from a USB port on my PC hooked up to serial monitor, this sketch works fine. I can observe the status LED going to READY‑TO‑PAIR after setting the Wifi credentials and resetting the ESP32. 

However, when I power the dev kit using the 5V external power supply pin, it stays in CONNECTING over and over again. I don't have a good way to debug this, because I can't hook up the serial monitor without accidentally supplying 5V power over the USB port. 

Other sketches which use the onboard WiFi and not HomeSpan are working fine. Any ideas?

**Comment by HomeSpan** [comment]
I think this is a result of how some boards are designed.  Based on the schematics of the HiLetgo shown on the Amazon web site, if you power the board via the 5V input, the USB chip receives no power at all, which would seem to be fine since you don't need the Serial Monitor if you're not plugged into a USB port.  However, HomeSpan is always polling for input from the serial port to see if you type in any commands from the Serial Monitor.  For many boards there is a pull-up (or pull-down) as needed on some of the USB chip outputs to make sure that when the USB chip is not being powered, the ESP32 thinks there is no data available and **does not** try to read anything.  But on some boards, the lines are left floating and the ESP32 thinks there is data available to be read.

For many sketches this is not a problem.  But since HomeSpan is always polling for serial data, if the ESP32 says there is serial data to be read, it tries to read it.  But HomeSpan never exits from the reading routing because the ESP32 always thinks there is more data to be read.

Other users that have reported this problem have solved by placing a pull-up (or pull-down) resistor on the appropriate ESP32 pins.  Since I don't have any boards that can be powered externally, I have not been able to test this myself.

One thing you can try is to eliminate the Serial.begin() in your sketch.  It may be that this prevents the ESP32 from reporting there is any data available, which allow HomeSpan to return immediately from checking for serial data.

If that does not work, you can try to comment-out the code in the HomeSpan library that checks for Serial data.  It is found on lines 218-221 of the file HomeSpan.cpp:

```C++
  if(Serial.available()){
    readSerial(cBuf,64);
    processSerialCommand(cBuf);
  }
```

Note I'm making a number of assumptions about the cause of the problem - it may be unrelated to the USB, but it's the only thing I can think of.

**Comment by HomeSpan** [comment]
Follow-up:  there is a longer discussion about this problem at issue #131.  One thing I forgot is that I may have identified a solution, but could not test.  Try adding the line: `pinMode(3,INPUT_PULLUP);` directly AFTER Serial.begin() and see if that works.

**Comment by z3ugma** [comment]
I can confirm that removing `Serial.begin()` from my sketch has resolved the problem. I can also volunteer to test putting pin 3 in INPUT_PULLUP mode with my dev board if you'd like me to try, @HomeSpan ?

**Comment by HomeSpan** [comment]
Yes, can you try adding `pinMode(3,INPUT_PULLUP);` right after `Serial.begin()` to see if that solves the problem as well?

**Comment by z3ugma** [comment]
Setting pin 3 to `INPUT_PULLUP` worked to resolve letting HomeSpan run from external power on my HiLetgo ESP-WROOM-32 ESP32 ESP-32S dev kit.

I gather that the reason to do this is that pin 3 is attached to Serial RXD and is variously called U0, RX, RX0 on mine and other dev boards, such as: 

<img width="145" alt="image" src="https://user-images.githubusercontent.com/6099983/208686860-edcf3f89-c7b0-4f13-a7ab-08f641e7ee97.png">

<img width="184" alt="image" src="https://user-images.githubusercontent.com/6099983/208687066-e34b8f59-bfce-4cd7-9c64-55ec00c0c847.png">

And so pulling it up makes sure that `Serial.available()` will return `false`.

**Comment by HomeSpan** [comment]
Thanks!  This is very good news.  Does setting the pin to INPUT_PULLUP interfere with the use of the Serial Monitor at all, or does everything still work as expected?

And you are correct that GPIO3 is the default RX pin for UART 0 on the ESP32.  This pin is not usually exposed on most boards since it's dedicated for Serial use, though this can be overridden by the user if needed.  There is a (very) slight performance gain by using pin 3 rather than having the ESP32 assign a different pin.

The U0_RXD pin is different on the ESP32-S2/S3 and the ESP32-C3, but starting with Board Manager 2.0.1 there seems to be a macro defined for each board, U0RXD_GPIO_NUM, that provides the pin number.
