### ISSUE TITLE
Cohabitation with existing code/project

### ISSUE THREAD

**Issue by simkard69** [HomeSpan/HomeSpan#468]
Hello,

I was wondering how is it possible to only use a fragment/part of HomeSpan in order to add it on top of an existing project ?

Let say I already have an ESP32 project with WifiManager and the (famous) AsyncWebServer from [https://github.com/me-no-dev/ESPAsyncWebServer](url) + some customization/settings and other code that is needed to control an old Mitsubishi Electrics A/C heatpump.
I just want to add HomeKit features without using the whole package which takes ownership of some mandatory features of mine (like WiFi, CLI, etc etc ...)

Can you please help me ?

Thanks

**Comment by HomeSpan** [comment]
HomeSpan was designed to be the base into which you add in logic to control appliances rather than the other way around.  It might be possible to extract portions of HomeSPan and embed into your existing project, but this would likely require a lot of work.

Also note that HomeKit itself requires a lot of non-standard protocols.  For example, unlike standard web connections, in which a web server receives a request, processes the URL, and then terminates the connections, HomeKit requires its devices to keep connections open and manage their resources _indefinitely_.  This is because HomeKit devices need to communicate unsolicted outbound data back to the HomeApp on an ad hoc basis (such as when you turn on a light using a switch).  The HomeKit protocol does not allow a device to open a connection to the Home App and report an update. Instead the device needs to use an existing connection that was previously established from the Home App (or a Home Hub) to the device, after HomeKit-specific encryption and handshaking is verified.  It may be possible to use ESPAsyncWebServer to do this type of reverse communication, but when I looked at that library a while ago it did not seem apparent.

Finally, there is a LOT you can customize in HomeSpan - it may not be that hard to add in your logic to control the A/C heat pump.
