### ISSUE TITLE
Carbon Dioxide characteristics for AirQualitySensor service

### ISSUE THREAD

**Issue by oleksiikutuzov** [HomeSpan/HomeSpan#469]
This is probably something else that changed under the hood, but seems to be working fine. (I guess I have even seen it in some revision of the HAP specification, but in the latest publicly available R2 it doesn't seem to be the case). 

HomeSpan shows warnings when using `CarbonDioxideLevel` and `CarbonDioxidePeakLevel` characteristics with `AirQualitySensor` service, but they are working fine and the Home App recognizes them as a separate subsection on the accessory page. 

<img src="https://user-images.githubusercontent.com/8535871/209579615-fb6dbf4d-942b-43d5-9176-fa7018a200c1.jpeg" width="300px">

**Comment by HomeSpan** [comment]
The Warning messages are based on HAP-R2 required/optional Characteristics.  In earlier versions of HomeSpan I threw fatal errors since the Home App would usually fail if an unexpected Characteristic was included in a Service.  However, Apple seems to have loosened this a lot over the years and now the Home App either renders something sensibly, or simply ignores an unexpected Characteristic. 

The HomeSpan Warnings are purely information and can be safely ignored if the Home App is properly rendering the Characteristic (as it seems to be above).

**Comment by oleksiikutuzov** [comment]
Yeah, I just looked at the latest commits in the dev branch and thought to let you know about such behavior in case you'd want to add those characteristics as compatible with that service. Otherwise, the issue can be closed then.

**Comment by HomeSpan** [comment]
Since there are likely a large number of Characteristic/Service combination that work even though they are not consistent with HAP-R2, I think it would make sense to keep the warnings as is for now - just a flag indicating something is not consistent with HAP-R2.  Ideally Apple would update HAP, or perhaps release a public version of their prop specs, which I'm guessing is constantly updated (though perhaps even commercial manufacturers have the same issues).
