### ISSUE TITLE
loose automations when updating the sketch

### ISSUE THREAD

**Issue by Olivierbkk** [HomeSpan/HomeSpan#491]
Hi, this may be a noob question (because I'm a noob here) but every time I modify the sketch and re-upload it, I need to pair again the bridge and I loose all automations etc in homekit... Am I missing something obvious?

**Comment by HomeSpan** [comment]
Adding/changing Services and Characteristics within an Accessory, or changing the order of the Accessories often requires re-pairing since HomeKit "remembers" each device it connects to, and often gets confused if the configuration of the device changes afterwards.

Are you running in bridge mode (where the first accessory does not contain any functional services)?  This sometimes (they not always) reduces the need to repair.

**Comment by danilkorotkov** [comment]
Full chip erase enabled?

**Comment by HomeSpan** [comment]
Sorry @Olivierbkk, maybe I misunderstood the issue.  Are you saying that whenever you upload a sketch to a device that was already paired and working, HomeSpan reports that it is no longer paired?  If so, @danilkorotkov is correct - check to make sure when you upload your sketch you have not enabled "erase flash" in the Arduino IDE.  This will erase all wifi and all pairing data.

**Comment by Olivierbkk** [comment]
that's it, thanks you guys!

I am running in bridge mode btw
