### ISSUE TITLE
Contact sensor not triggering the alarm at boot if open

### ISSUE THREAD

**Issue by Olivierbkk** [HomeSpan/HomeSpan#495]
Hi,

I am trying to have a contact sensor to trigger a Security System via an HK automation. Basically if the contact opens, it triggers the SS. 

It works fine but the problem is if the power is down while the contact opens, the SS is not triggered when the power comes back up, I have to close the contact and reopen it to make it trigger the SS.

I tried a few things which I commented below but nothing works.

Any idea on how to solve this?

here is my code:

```C
struct DEV_ContactSensor : Service::ContactSensor {

 int sensorPin;

  const int DEBOUNCE_DELAY = 50;                                    // FOR DEBOUNCE: the debounce time; increase if the output flickers
  int lastSteadyState;                                              // FOR DEBOUNCE: the previous steady state from the input pin
  int lastFlickerableState;                                         // FOR DEBOUNCE: the previous flickerable state from the input pin
  int currentState;                                                 // FOR DEBOUNCE: the current reading from the input pin
  unsigned long lastDebounceTime = 0;                               // FOR DEBOUNCE: the last time the output pin was toggled based on millis()

  SpanCharacteristic *sensorState;                                  // reference to the Current sensor state Characteristic
  
  DEV_ContactSensor(int sPin) : Service::ContactSensor(){           // constructor() method
    sensorState=new Characteristic::ContactSensorState();          // instantiate the Current sensor state Characteristic
    this->sensorPin = sPin;
    pinMode(sensorPin,INPUT_PULLUP);                                // Pullup type needed for debouncing

    Serial.print("Configuring Contact Sensor");                     // initialization message
    Serial.print("\n");

  } // end constructor

  boolean update(){   // THIS IS STILL A PROBLEM, THERE IS NO SECURITY SYSTEM TRIGGER IF REBOOT AND CONTACT IS OPEN, I TRIED A FEW THINGS THAT I COMMENTED BELOW AND NOTHING WORKS


    //sensorState->setVal(digitalRead(sensorPin));                           // 
    //sensorState->getNewVal();
/*
    if (digitalRead(sensorPin) == LOW){
      sensorState->setVal(HIGH);
      delay (1000);
    }
  */  
    sensorState->setVal(digitalRead(sensorPin));                           // 

    return(true);                               // return true
  
  } // update


  void loop(){

    currentState = digitalRead(sensorPin);                          // read the state of the switch/button:

    if (currentState != lastFlickerableState) {                     // If the switch/button changed, due to noise or pressing:
      lastDebounceTime = millis();                                  // reset the debouncing timer - millis() returns the number of milliseconds passed since the board began running the current program. This number will overflow and go back to zero after approximately 50 days
      lastFlickerableState = currentState;                          // save the last flickerable state
    }

    if ((millis() - lastDebounceTime) > DEBOUNCE_DELAY) {

      if((lastSteadyState == HIGH && currentState == LOW) || (lastSteadyState == LOW && currentState == HIGH)) {
        Serial.println("The sensor has changed");
        sensorState->setVal(currentState);                           // 
      }

      lastSteadyState = currentState;                               // save the the last steady state
    }

  } // loop
  
};
```

**Comment by HomeSpan** [comment]
In the above sketch you have `sensorState->setVal(digitalRead(sensorPin));` placed in the `update()` method.  This will never be called.  HomeSpan calls the `update()` method in response to a user requesting an *update* of a Characteristic from the Home App.  The `update()` method is where you provide code to reflect Tile presses on the Home App.

ContactSensorState is a read-only Characteristic. Users cannot change this Characteristic by pressing a Tile on the Home App.  In fact, all of the Characteristics (even the optional ones) associated with the Contact Sensor Service are read-only, so HomeSpan will never call `update()` --- you should not need to define it at all (see for example Tutorial 12 - Service Loops).

In contrast, the `loop()` method for every Service is called once each time `homeSpan.poll()` is run.  Calls to the `loop()` method are unrelated as to whether or not there was previously a call to `update()` in response to a user Tile press in the Home App.  In the case of a Contact Sensor, this is where all the logic should be.

**Comment by Olivierbkk** [comment]
Thanks fo the very clear explanation about the `update()` method. Actually I tried adding that in the code because nothing seemed to be working.

I went back to basics as per the code below but I still have the same issue, the sensor status is updated correctly in the Home App but it still does not trigger the automation on reboot if the sensor state has changed while the power is down.

Here is how I test:
- I have an automation in the Home App to turn on a switch when the contact sensor opens
- if I close and open the sensor with the ESP32 powered on, the automation works well and the switch is turned on by the automation
- if I close the sensor while the ESP32 is powered on, then turn off the power, open the sensor while the power is down, then power up the ESP32, the contact sensor state will be displayed correctly in the Home App after a while but the automation to turn on the switch in the Home App is not triggered - then if I close and reopen the contact the automation is finally triggered.

> In contrast, the loop() method for every Service is called once each time homeSpan.poll() is run. Calls to the loop() method are unrelated as to whether or not there was previously a call to update() in response to a user Tile press in the Home App. In the case of a Contact Sensor, this is where all the logic should be.

I was under the impression that I should not have the `sensorState->setVal(digitalRead(sensorPin));` in the loop to avoid flooding the network, is that correct?

```C
struct DEV_ContactSensor : Service::ContactSensor {

 int sensorPin;

  const int DEBOUNCE_DELAY = 50;                                    // FOR DEBOUNCE: the debounce time; increase if the output flickers
  int lastSteadyState;                                              // FOR DEBOUNCE: the previous steady state from the input pin
  int lastFlickerableState;                                         // FOR DEBOUNCE: the previous flickerable state from the input pin
  int currentState;                                                 // FOR DEBOUNCE: the current reading from the input pin
  unsigned long lastDebounceTime = 0;                               // FOR DEBOUNCE: the last time the output pin was toggled based on millis()

  SpanCharacteristic *sensorState;                                  // reference to the Current sensor state Characteristic
  
  DEV_ContactSensor(int sPin) : Service::ContactSensor(){           // constructor() method
    sensorState=new Characteristic::ContactSensorState();          // instantiate the Current sensor state Characteristic
    this->sensorPin = sPin;
    pinMode(sensorPin,INPUT_PULLUP);                                // Pullup type needed for debouncing

    Serial.print("Configuring Contact Sensor");                     // initialization message
    Serial.print("\n");
  } // end constructor

  void loop(){

    currentState = digitalRead(sensorPin);                          // read the state of the switch/button:

    if (currentState != lastFlickerableState) {                     // If the switch/button changed, due to noise or pressing:
      lastDebounceTime = millis();                                  // reset the debouncing timer - millis() returns the number of milliseconds passed since the board began running the current program. This number will overflow and go back to zero after approximately 50 days
      lastFlickerableState = currentState;                          // save the last flickerable state
    }

    if ((millis() - lastDebounceTime) > DEBOUNCE_DELAY) {

      if((lastSteadyState == HIGH && currentState == LOW) || (lastSteadyState == LOW && currentState == HIGH)) {
        Serial.println("The sensor has changed");
        sensorState->setVal(currentState);                           // 
      }

      lastSteadyState = currentState;                               // save the the last steady state
    }

  } // loop
  
};
```

**Comment by HomeSpan** [comment]
Try setting the initial value of SensorState to the value of the sensorPin at startup this way:

`sensorState=new Characteristic::ContactSensorState(digitalRead(sensorPin));`

**Comment by Olivierbkk** [comment]
thanks for the suggestion, I changed the constructor as follows (the rest is the same):

```C
  DEV_ContactSensor(int sPin) : Service::ContactSensor(){           // constructor() method
    //sensorState=new Characteristic::ContactSensorState();           // instantiate the Current sensor state Characteristic
    this->sensorPin = sPin;
    pinMode(sensorPin,INPUT_PULLUP);                                // Pullup type needed for debouncing
    sensorState=new Characteristic::ContactSensorState(digitalRead(sensorPin));
    Serial.print("Configuring Contact Sensor on pin ");             // initialization message
    Serial.print(sensorPin);                                        // initialization message
    Serial.print("\n");

    //sensorState->setVal(digitalRead(sensorPin));

  } // end constructor
```

the result is the same as described in my last post

**Comment by HomeSpan** [comment]
I've experimented a bit and the root of the problem may be the way HomeKit processes automations.  It seems that automations are based on changes in the state of a Characteristic, not the absolute value of the Characteristic.  When you cycle the power and HomeKit eventually connects to the device, it reads the current state of the Contact Sensor, but this does not trigger any automations.  Rather, the state needs to flip from open to close, or close to open, in order to trigger an automation.

In principle you could always initialize a Characteristic to be the opposite of what it should be, and then follow-up with a setVal() with the correct state, thereby triggering a "change" from the perspective of the Home App.  But therein lies another problem with HomeKit - communication is only one way.  Devices cannot transmit anything to HomeKit until HomeKit first initiates a connection, and then "subscribes" to listen for changes to a Characteristic.  If you power down a device and turn it back on, HomeKit may not reconnect for quite some time unless you open the Home App or issue a Siri command.  Thus, even if you do call setVal() upon boot up to "flip" the state of a Characteristic, there will no HomeKit controllers listening and setVal() can't end anything, though the internal state of Characteristic will reflect the change.

I've thought about some potential solutions, such as having setVal() queue all requests until there is at least one HomeKit controller connected and actively listening for events from the device.  But this wouldn't solve the problem of having to wait (possibly a long time) before a controller decides to connect to HomeKit if you don't open the Home App or send a Siri command.

I'll need to give more thought to this --- not sure of the ideal way to solve.

**Comment by Olivierbkk** [comment]
not sure if it would help but I had the same issue with a Homebridge plugin and the problem was fixed, here is the link to the plugin: https://github.com/ebaauw/homebridge-rpi 

and here is the related thread: https://github.com/ebaauw/homebridge-rpi/issues/151

**Comment by HomeSpan** [comment]
Thanks - I read through the thread but not sure if I understand the RPi issue correctly.  It seems to be more about the RPi hardware and properly reading GPIOs upon initialization.  There is no problem with reading the correct state of a rocker switch in HomeSpan upon initialization.  The problem is what to do with this information if you want to trigger an automation.  Absent the automation, the Home App (or a Home Hub) will eventually re-connect to HomeSpan and correctly read the current state of the rocker switch.  But that's not sufficient for triggering an automation.

I think what you would need to do is save the ContactSensorState in memory so that it reflects the last known state, instead of the current state.  This is very easy to do - simply set the second parameter in the constructor to "true."  HomeSpan automatically saves the state and sets it accordingly upon start-up.

The next step is what needs more work:  You need to delay the use of setVal() to change the state of the rocker switch to reflect the actual state until such time that HomeKit has connected to your device.  There are a number of ways to do that, but it requires a core code change so you know when HomeKit has established a connection.  I'm thinking through the best way to accomplish this.
