### ISSUE TITLE
Accessories unresponsive in Homekit after a few days

### ISSUE THREAD

**Issue by AndreasVerhoeven** [HomeSpan/HomeSpan#497]
I'm running homespan on an ESP32 and every few days (like 3 to 4 days) the exposed accessories become unresponsive in homekit. The device seems perfectly functional tho:
 - the weblog is reachable (disabled NTP timing also)
 - the wifi connection is good (-50dB)
 - the device pings fine (wifi sleep mode is disabled)
  
It's only homekit that cannot connect to the homespan accessories when it's connected standalone. I haven't been able to trigger this when there's a serial connection over usb also, mainly because of the long time it takes for this issue to show up.

Any pointer or clue on how to debug this?

**Comment by HomeSpan** [comment]
A few things to check:

* are you using `setVal()` to set Characteristic values?  If so, make sure you are always setting them within the correct range.  Setting any Characteristic out of range will cause HomeKit to disconnect from your device.

* are you using a mesh router?  If so, there are known interactions problems with mesh router IGMP settings and HomeKit.  Your router may have a way of enabling IGMP filtering that usually solves this problem.

* check to make sure you are using the latest version of the Arduino-ESP32 board manager (version 2.0.5 or 2.0.6) as well as there latest version of HomeSpan (1.7.0)

**Comment by AndreasVerhoeven** [comment]
Thanks for the quick reply:

 - setVal() is not used; the device becomes unresponsive out of the blue without any accessories being controlled
 -  I have an RT-AX58U Asus Router that works in regular router mode, not in mesh node. IGMP Snooping is disabled.
 -  `Arduino-ESP Version: | 2.0.5`  and `HomeSpan Version: | 1.7.0`.
 
It's also only Homespan devices that go unresponsive; all other wifi based devices in homekit stay connected.

Any other hints on how to debug this maybe?

**Comment by AndreasVerhoeven** [comment]
I've also ensure that the homespan has an MDNS-entry for `_hap._tcp` when it gets unresponsive

**Comment by HomeSpan** [comment]
My next suggestion was going to be to check the MDNS-entry (one of the more common problems), but you've already ruled that out.   Unfortunately these types of intermittent response issues can be very hard to track down.

If the weblog is working while at the same time the device has become non-responsive from HomeKit, this also rules out any issues with the sketch hanging.  I assume that the weblog does not show a bunch of WiFi disconnect/re-connects?

To make sure the problem is not related to your sketch, you may want to try running Tutorial Example 1 and see if the issue still arises.  If so, then you know it's not related at all to your specific sketch.  

Another thing to try is to unpair the device, type 'E' into the Serial Monitor to clear all NVS entries, and re-pair the device (you'll need to re-type your WiFi credentials as well).  If the Home App or your HomeKit Hub was incorrectly caching any information about your device, this should cause it to view your device as a new accessory.  You can also try using the "Erase Flash" option in the Arduino IDE when you upload your sketch - this will ensure everything is completely erased and you are starting fresh.

On occasion I have had issues where my router is the source of the problem.  This can occur if I inadvertently use the same name for two different HomeSpan devices (by overriding the suffix).  A reboot of my router is usually the only thing that solves this particular problem.
