### ISSUE TITLE
Split up Device in .h/.cpp files with custom characteristic

### ISSUE THREAD

**Issue by Deprinz2015** [HomeSpan/HomeSpan#499]
Hey, first of all, your work is awesome and i love, that you're still actively updating und developing!

I have an addressable LED-Strip, where i want to control the currently playing effect over HomeKit. The different effects can be accessed via numerical IDs. So far, HomeKit can control the Strip as a whole, just like your normal LED-Lightbulb. Now onto the effects.
I started with adding a custom characteristic for the effect ID. While linking it gives the error, that it has multiple definitions.
As far as i can see, that happens when i split up the struct for my LED-Strip Device in header and source files.

I tested it with the custom service example you provided, which worked flawlessly. But then i tried customizing it to fit my project structure. That's where it broke.

I split up the definition of the device into a header file at 'include/HomeSpan/PressureSensor.h':

```
#ifndef DREAMLIGHTS_PRESSURESENSOR_H
#define DREAMLIGHTS_PRESSURESENSOR_H

#include "HomeSpan.h"

CUSTOM_SERV(AtmosphericPressureSensor, E863F00A-079E-48FF-8F27-9C2605A29F52);

CUSTOM_CHAR(AtmosphericPressure, E863F10F-079E-48FF-8F27-9C2605A29F52, PR+EV, FLOAT, 1013, 700, 1200, false);

struct PressureSensor : Service::AtmosphericPressureSensor {         // A standalone Air Pressure Sensor

    Characteristic::AtmosphericPressure pressure;                      // Eve Air Pressure with range 700-1200 hPa (millibars), where 1 atm=1013 hPa

    PressureSensor();

    void loop() override;

}; // end PressureSensor

#endif //DREAMLIGHTS_PRESSURESENSOR_H
```

and a source file at 'src/HomeSpan/PressureSensor.cpp':

```
#include "HomeSpan/PressureSensor.h"

PressureSensor::PressureSensor(): Service::AtmosphericPressureSensor{} {
    // Init Code...
}

void PressureSensor::loop() {
    // loop Code...
}
```

When i put everything inside the header file, that works just fine, but i'd like to split it up to organize my files for this fairly large project.
Also this splitting up works with the Standard Characteristics, as i have it already in place, just with normal Light-Characteristics.

Thank you in advance for any help.

**Comment by HomeSpan** [comment]
Are you using multiple .cpp files?  The reasons I ask is that the "include guard" (DREAMLIGHTS_PRESSURESENSOR_H) only prevents each .cpp file from individually calling CUSTOM_CHAR() more than once while compiling (which would happen if you had multiple includes in each .cpp), but it does not prevent separate .cpp files from each calling CUSTOM_CHAR().  This is because defining DREAMLIGHTS_PRESSURESENSOR_H only applies to the .cpp file in which it is included, and does not carry over from one .cpp to another.  As a result, the linker will find repeat definitions from each .cpp file.

**Comment by Deprinz2015** [comment]
I'm using multiple .cpp files, yes, but only one for this device. This class does get included in another file, to register the device.
What should i change for it to work? Are there other methods of "include-guarding", so that i can still split up the .h and .cpp files?

**Comment by HomeSpan** [comment]
Are you using the Arduino IDE or PlatformIO?

**Comment by Deprinz2015** [comment]
PlatformIO with CLion

**Comment by HomeSpan** [comment]
I was able to reproduce the issue and tracked down the problem.  The CUSTOM_CHAR() macro does two things.  First, it instantiates a new HapChar, which is an internal HomeSpan representation of the Characteristic.  Then it defines a structure that is based on that Characteristic.  It's the structure you wind up using in your code.

It's okay to have multiple definitions of the same structure in different .cpp files, but it's not okay to have multiple instantiations of the same variable, namely two instantiations of the same HapChar.

To solve this, I created a new macro CUSTOM_CHAR_EXTERN() that is similar to the CUSTOM_CHAR() except that instead of instantiating a new HapChar, it is defined as an external reference.  The way you use this is as follows:

Create two files, *common.cpp* and *common.h* (they could be named anything - I'm just using these as an example).  In *common.cpp*, use CUSTOM_CHAR() to create all your custom Characteristics.  Don't forget to add `#include "HomeSpan.h" to the top of the file.  Then, do the exact same thing in *common.h*, except that instead of using CUSTOM_CHAR(), use CUSTOM_CHAR_EXTERN().  This *declares* the custom Characteristics without *redefining* the internal HapChar that is causing the issue.

Finally, simply add `#include "common.h"` to any .cpp file to make use of the custom Characteristics.  DO NOT include *common.h* in *common.cpp*, otherwise you will get a redefinition error.

I have not yet added the CUSTOM_CHAR_EXTERN() macro to HomeSpan, but below is the definition.  Copy this into your *common.h* file and then use CUSTOM_CHAR_EXTERN() as described above:

```C++

#define CUSTOM_CHAR_EXTERN(NAME,UUID,PERMISISONS,FORMAT,DEFVAL,MINVAL,MAXVAL,STATIC_RANGE) \
  extern HapChar _CUSTOM_##NAME; \
  namespace Characteristic { struct NAME : SpanCharacteristic { NAME(FORMAT##_t val=DEFVAL, boolean nvsStore=false) : SpanCharacteristic {&_CUSTOM_##NAME,true} { init(val,nvsStore,(FORMAT##_t)MINVAL,(FORMAT##_t)MAXVAL); } }; }
```

If this works based on your testing/feedback, I'll add the new macro (as well as ones for CUSTOM_SERV_EXTERN, etc) to the dev branch of the HomeSpan library for further testing and verification.

**Comment by Deprinz2015** [comment]
I Just tested it with a simple build. I haven't tested it on the Board or with added complexity, but at least the build process finished without errors. That seems to be the solution, Thank you!
