### ISSUE TITLE
wifi extender

### ISSUE THREAD

**Issue by danilkorotkov** [HomeSpan/HomeSpan#553]
there is a little bug with main wifi ap & wifi extender with the same SSID
```
Nr | SSID                             | RSSI | CH | Encryption
1 | domik                            |  -58 | 11 | WPA2 //main AP
2 | domik                            |  -87 | 11 | WPA2 //extender
```
case 1: if i reboot main AP, board establishes the connection with the weak strength extender but works
case 2: if main home power restores, the main AP boots longer than the extender and weblog works without a time server.

it would be nice to create homespan method for switching AP or reinit a timeserver after internet connection established

**Comment by danilkorotkov** [comment]
https://hieromon.github.io/AutoConnect/adconnection.html

**Comment by HomeSpan** [comment]
To address the Time Server issue I changed the initialization code so that instead of blocking, HomeSpan spawns a new task in the background that tries to acquire the time from the specified time server.   Web Log entries have been added to reflect when the process begins, as well as when the time has been acquired.  If the time has not been acquired after 2 minutes, HomeSpan give up (and reports that to the Web Log as well).  As before, you can set this timeout period to any desired value.

I think this should address your issue above - HomeSpan will keep trying (for up to 2 minutes or more) to set the time.  Normally waiting this long would be problematic since this process blocked HomeSpan from running.  But by spawning a separate task, this is no longer a constraint.

I've tested this on both an ESP32 and ESP32-C3.  HomeSpan operates normally even with the timeserver initialization running in the background.

New code is in the dev branch as usual.  Please feel free to give it a try and let me know if this solves the problem.

**Comment by danilkorotkov** [comment]
thank you
i will test with the stable release

**Comment by HomeSpan** [comment]
Version 1.8.0 has been release and includes this feature.
