### ISSUE TITLE
CurrentHeatingCoolingState default value does not work

### ISSUE THREAD

**Issue by barisonal** [HomeSpan/HomeSpan#555]
I tried to use CurrentHeatingCoolingState by giving default value 0.

`Characteristic::CurrentHeatingCoolingState currentState{0,true};`

But it is being initialized with value 1 in every restart. 

I fixed that problem by setting it to 0 `currentState.setVal(0);` in constructor.

**Comment by danilkorotkov** [comment]
Characteristic::CurrentHeatingCoolingState currentState(0,true);

**Comment by barisonal** [comment]
> Characteristic::CurrentHeatingCoolingState currentState(0,true);

Nope, it works with {} characters, not (). 

You can check the sample in [HomeSpanReferenceSketches](https://github.com/HomeSpan/HomeSpanReferenceSketches/tree/main/Thermostat)

**Comment by danilkorotkov** [comment]
yes, my bad
try to flash sketch with full chip erase

**Comment by HomeSpan** [comment]
The problem is that you are setting the second parameter to *true*.  If you want the initial state to always be zero, simply use:

`Characteristic::CurrentHeatingCoolingState currentState{0};`

If you add a second parameter and set to *true,* this tells HomeSpan to save and **restore** the value in NVS, which means when HomeSpan first starts **the value is set to whatever it was before rebooting**.  Whenever the the second parameter is set to *true*, the first parameter is only used if HomeSpan does not find any saved values in NVS (in which case it will set the value to the first parameter=zero).  Note you can erase all stored NVS values by typing 'V' into the CLI.

Upon re-reading the documentation, I realize that the above is not all that clear - I'll update the docs to better reflect this.

Regarding whether to use {} or (), it depends on where the statement is.  If you declare a variable inside a class or structure, but not within any method, and want to initialize it, you need to use {}.  If the variable is created or initialized inside a class or structure method (including the constructor), then use ().

**Comment by barisonal** [comment]
Oh okay! It worked fine. Thank you.
