### ISSUE TITLE
I2C examples

### ISSUE THREAD

**Issue by Olivierbkk** [HomeSpan/HomeSpan#574]
Hello,
Is there any available examples of how to use I2C for a contact sensor and led for example?

I had a look at the tempsensorI2C example but it's quite too far from what I need for me to adapt it to a contact sensor or a led device.

How many devices max can we implement in one instance of HomeSpan?

thanks

**Comment by danilkorotkov** [comment]
https://github.com/danilkorotkov/recuperator
i2c counter & lcd

**Comment by Olivierbkk** [comment]
thanks, it still looks quite complex to me... all I need is to add more gpio to my esp for simple devices, no fancy temperature or fan speed or screen, just contact sensors and led.

I have to wait for my i2c module to arrive from aliexpress now, I ordered a PCF8575 Module

**Comment by HomeSpan** [comment]
It sounds like you are not trying to control an I2C LED or I2C Contact Sensor, but rather you have ordered a generic I2C pin extender that you wish to use for connecting a standard LED and Contact Sensor switch.  Since every pin extender is different (some use I2C, others use a multiplexer), HomeSpan does not have a generic library to control them.  However, they usually come with their own library that you can use without needing to know the details.  For example, the module you mention above is also sold by Adafruit and comes its own library that handles all the I2C calls for you.

Once you get the pin extender working generically, adding a contact sensor or LED depends on how the pin extender hardware works and what library calls you will need to use.  I recommend first creating a standalone non-HomeSpan sketch to test the pin-extender's library and make sure you can turn on/off an LED and read a contact sensor using the pin extender's methods.

Once that's done, adding to HomeSpan is quite easy.  Simply create a contact sensor service and an LED service (example 5 shows you how to create a working LED).  BUT...instead of turning on/off the LED by setting the LED pin high/low using digitalWrite(), you turn it on/off using whatever function/method calls your pin extender expects, as determined from the standalone sketch.

Regarding the maximum number of devices, HomeKit is supposed to support 150 Accessories per bridge device but in practice HomeSpan running on the ESP32 does not have sufficient memory to handle that many.  HomeSpan currently imposes an internal limit of 41 instances of SpanAccessory().

**Comment by Olivierbkk** [comment]
> It sounds like you are not trying to control an I2C LED or I2C Contact Sensor, but rather you have ordered a generic I2C pin extender that you wish to use for connecting a standard LED and Contact Sensor switch. 

yes that's correct and thanks for the advice, I will try to use that outside of HomeSpan first and see how it works

> Regarding the maximum number of devices, HomeKit is supposed to support 150 Accessories per bridge device but in practice HomeSpan running on the ESP32 does not have sufficient memory to handle that many. HomeSpan currently imposes an internal limit of 41 instances of SpanAccessory().

thanks, that's good to know, currently having two ESP32 running HomeSpan with 13 accessories each, some accessories using 3 or more gpio. The on board gpio are pretty much maxed out and I need to add more, that's why I need more gpio and hence the idea of using I2C
