### ISSUE TITLE
Shift register

### ISSUE THREAD

**Issue by Nezaemmy** [HomeSpan/HomeSpan#581]
I'm able to control the output of 74hc595 using Example 5 (WorkingLED) by changing 

digitalWrite(ledPin,power->getNewVal()); to mh.set(ledPin,power->getNewVal());

I tried to use the same in Example 15 (RealPushButtons) it doesn't work.
Is there any suggestion I can use to control output by using example 15?

**Comment by HomeSpan** [comment]
Example 15 uses a *dimmable* LED controlled by the LedPin class which generates a PWM signal to set the brightness of the LED.  The 74hc595 does not provide PWM output and cannot be used to control a dimmable LED.  However, if your purpose of using Example 15 was for the SpanButton functionality (not the dimmable LED), you can modify Example 15 to use the simple on/off LED code from Example 5 (or alternatively add the SpanButton code from Example 15 into Example 5).

**Comment by Nezaemmy** [comment]
Thank you @HomeSpan, I modified the code on example 15 to remain only on/off, and it is working. 
because example 5 uses digitalWrite is differs to example 15 uses      ledPin->set(power->getNewVal()); 
Every time I try to change ledPin-> to mh.set like in example 5 I get an error.
My challenge is to find where I can modifier

**Comment by HomeSpan** [comment]
Sorry, I'm not sure I understand --- can you repeat was is and what is not working, and the desired end goal?

**Comment by Nezaemmy** [comment]
Sorry, I want to use example 5 with push button to control the output of 74hc595. I was able to do it without push button by changing digitalWrite(ledPin,power->getNewVal()); to mh.set(ledPin,power->getNewVal());

**Comment by HomeSpan** [comment]
Note that the variable *ledPin* means something different in Example 5 as it does in Example 15.  In Example 5 *ledPin* is an integer that you pass to the **DEV_LED** constructor.  It represents the actual pin number you want to use (e.g. 21), which is why it works with `mh.set()` (assuming the first parameter in `mh.set()` is supposed to be a pin number).

In contrast, the variable *ledPin* in Example 15 is instantiation of the **LedPin** class that contains all the PWM logic mentioned above.  When you pass an actual pin number to the **DEV_DimmableLED** constructor, the code creates the *ledPin* object.  This is not a number and cannot be used in `mh.set()`.  If you want to used Example 15 as your starting point, you need to remove all the code where *ledPin* is instantiated as an **LedPin** object, and replace with *ledPin* being just a plain integer number.

**Comment by Nezaemmy** [comment]
Thank you @HomeSpan
