### ISSUE TITLE
Problem with wifi setting in example 6.

### ISSUE THREAD

**Issue by Jir0012** [HomeSpan/HomeSpan#583]
Hi, I have tried to connect esp32 to wifi using example 6, but the wifi setting didn't come up when I return W. It did when I return using example 1, please tell me if I have missed anything. Thank you.

**Comment by HomeSpan** [comment]
Is the program completely frozen, or is it just 'W' that is unresponsive.  For example, do you get proper responses from the 's' and 'i' commands?

**Comment by Jir0012** [comment]
I don't think the program is frozen, the serial monitor keeps on running. However, it also show no response to 'i' and 's' command, it works on example 1 though. I'm using XIAO_esp32C3 as my board. Actually I haven't soilder any LED to the board yet, I wonder if that matter.

**Comment by HomeSpan** [comment]
Example 1 does not use any ESP32 pins but Example 6 does.   Did you set the pins to ones that will be useable on your board?  I think the example uses pins 16 and 17, which are fine for the ESP32 but not for the ESP32-C3 since those pins are used for the USB serial connection (which would explain why the serial monitor is not responding).   For each example that uses pins make sure to set those to something that will work for your specific board.  Note is does not matter whether you actually connect something to those pins --- the example sketches will configure them anyway, and if there is a conflict with your specific board that will cause an issue.

**Comment by Jir0012** [comment]
It did fix the issue, thank you very much!
