### ISSUE TITLE
Question re: Apple Home "Upgrade"

### ISSUE THREAD

**Issue by Xorlent** [HomeSpan/HomeSpan#587]
In the latest iOS, Apple Home is prompting to upgrade the platform.  Has anyone performed this and confirmed functionality with Homespan-based devices?  I do see one caveat with the new platform that may affect users: iPad is no longer a compatible hub device.(https://support.apple.com/en-us/HT213481)

You can find this option under, "Software Update" in the home app's Settings menu.  

**Home Upgrade Available**
Home has a new underlying
architecture that will improve the
performance of your home.

**Comment by HomeSpan** [comment]
Many HomeKit users originally had significant problems with commercial HomeKit devices, as well as problems adding new users, retaining previous users, etc.  The problem was so bad that Apple subsequently released an update that prevented this upgrade from being performed.  Later they fixed the issue and re-instated the upgrade.   It's been quite a number of months so it's probably stable, but you never know for sure.  One thing to note is that every user, every device (iPhone, homePod, etc) needs to be on the latest versions of iOS to ensure things will work.

There is nothing specific to HomeSpan that would exacerbate or mitigate any problems - the issue seemed to effect all HomeKit devices.

I upgraded a number of months ago (when first released) and after lots of rebooting was able to get all my devices reconnected.  However, I was not able to add other users until Apple released subsequent patches.

**Comment by Xorlent** [comment]
Interesting, thank you Gregg.  Once I take the plunge, I'll report back if there are any undesired side effects.

**Comment by Xorlent** [comment]
Closing as not planned.

**Comment by Xorlent** [comment]
Closing
