### ISSUE TITLE
[question] Remote sensors using LoRa

### ISSUE THREAD

**Issue by homonto** [HomeSpan/HomeSpan#604]
Hi there,

So far I implemented your library with ESPNow and is working perfectly - it really is.
But now I would like to extend it to using LoRa - reason is obvious: longer distance between hub and sensor device.

Is there any simple way of replacing ESPNow still using your library with LoRa or do I have to redo everything?

I am mainly talking about this part of the code:
```

struct UpdateData : Service::AccessoryInformation
{
  SpanCharacteristic *md_version;

  SpanPoint *remoteData;
  const char *name;
  const char *macAddress;
  
  UpdateData(const char *name, const char*macAddress) : Service::AccessoryInformation()
  {
    this->name=name;
    this->macAddress=macAddress;
    new Characteristic::Identify();
    new Characteristic::Name(name);
    new Characteristic::SerialNumber(macAddress);  
    
    md_version    = new Characteristic::FirmwareRevision("");
    remoteData    = new SpanPoint(macAddress,0,sizeof(myData)); 
  }

  void loop()
  {                                     
    if(remoteData->get(&myData))
    {  
```

so here, using your library the trigger is when remoteData gets the data (incoming), right?
what and how to replace with (i.e.):

`if(remoteData->LoRa_received(&myData)`

Thank you

**Comment by HomeSpan** [comment]
The vast majority of the SpanPoint code is all specific to ESP-NOW (i.e. managing the WiFi channels, the ESP-NOW handling processes, etc.).  If you already have a LoRa library that can read data from the other device, I would treat this like a standalone sensor and insert whatever code is needed to read the sensor in the `loop()` method above (replacing the entirety of remoteData with some other command designed to read via LoRa).  You will likely need to perform some initialization to configure the LoRa as well, which could be done in the main setup() portion of the code, or could replace the line `remoteData = new SpanPoint()`, since that line is also specific to ESP-NOW.
