### ISSUE TITLE
SetRange for some Thermostat related Characteristics

### ISSUE THREAD

**Issue by HomeKidd** [HomeSpan/HomeSpan#606]
Hi!

I've tried to update [some Characteristics](https://github.com/HomeSpan/HomeSpan/blob/7ceee3fda066005aeb3dd90678dd25524d6d8244/src/Characteristics.h#L184C2-L184C67) with custom values but it looks like these are defined as static (_staticRange_) by HomeSpan. These CHs can be overwritten via HomeAccessorySimulator and using custom range make sense.

Like `TargetHeatingCoolingState`, which is also required (as linked service) for Valve Service with heating function, so setting valid values for only Heating is a must. Same thing applies for e.g.:  any AC unit (which uses HeatingCoolingState too) with only cooling, auto settings. So setting `TargetHeatingCoolingState` and `CurrentHeatingCoolingState` with `->setValidValues(2,  0, 2); // only auto & cool` is relevant.

**Comment by HomeSpan** [comment]
The `setRange` and `setValidValues` methods have different validation criteria.  The `staticRange` variable is only applicable to `setRange`.  The `setValidValues` method does not check `staticRange`.  It allows any UINT8, UINT16, UINT32, or INT Characteristic to be changed.  Is this not working for TargetHeatingCoolingState?

**Comment by HomeKidd** [comment]
I've checked it, but both valid values and setRange doesn't make any changes somehow.
What I'm trying to do is an AC unit with only cool and auto mode, so setting `TargetHeaterCoolerState` with `->setValidValues(2,  0, 2); ` on runtime, but before HomeSpan init. Same applies for `CoolingThresholdTemperature` and `HeatingThresholdTemperature`, setting these with `-> setRange(_config.ac_min_temp, _config.ac_max_temp, 1);` didn't update the values in Home app after rebooting. Both variables set before HomeSpan init. No Warnings, no errors.

```
     15:36:14.414 ->       ⇨ Characteristic CoolingThresholdTemperature(23):  IID=14, UUID="D", Perms=PR+PW+EV, Custom-Range=[0,50,1] (nvs)
     15:36:14.446 ->       ⇨ Characteristic HeatingThresholdTemperature(30):  IID=15, UUID="12", Perms=PR+PW+EV, Custom-Range=[0,50,1] (nvs)
```

But the temp range is still at 16-30 degC

**Comment by HomeSpan** [comment]
Are you trying to set the range to 10-32 degrees C?  In other words, are the values you are trying to set properly displayed in HomeSpan, but not reflected in the Home App?  Note you can double-check this by typing 'd' into the CLI - bit will show you exactly what is transmitted to the Home App, including any changes to valid values and ranges.

If all that looks correct, then the issue is mostly likely the Home App or your Home Hub caching information about the current configuration and not reflecting the new data.  The cure is unpair the device, create a new device ID by typing 'H' into the CLI after unpairing, and then repairing.  Type 'H' is important because that generates a new device ID so that the next time you pair, Home Kit will see a brand new device and not try to "remember" previous settings for the old device.

**Comment by HomeKidd** [comment]
Setting valid values for `TargetHeaterCoolerState ` and `CurrentHeaterCoolerState ` was successful, it was actually my mistake when checking conditions for including Heat mode or not, rookie mistake with the equal syntax operator 😂

BUT... changing the  `CoolingThresholdTemperature` and `HeatingThresholdTemperature` still not working normally,  printing out the summary information about the HAP Database shows the values (without any error/warning) but the Home app doesn't updated. Changing value range on runtime (technically before HomeSpan init) maybe requires   `HomeSpan.updateDatabase();` ? 
When I've changed the `min` `max` values, rebooted the device, the database shows the correct temperature range, Home app doesn't. Removing the accessory and re-adding it sometimes helped, sometimes not or not immediately...

**Comment by HomeSpan** [comment]
If you type 'd' into the Serial Monitor and it shows you the correct ranges, this means HomeSpan is sending the correct data to HomeKit.  If you close the Home App on your iPhone and re-open, it refreshes the database.  If you set Log Level 2, you can see the request and verify that the correct data is being transmitted.

Not sure why it is not updating on the Home App.  I just checked with my Thermostat Reference sketch and it seems to be respecting the custom range.

However, one thing to check: above you mentioned you only wanted Cooling, not Heating.  I just realized that Auto only makes sense if you have both Cooling and Heating enabled.  This is not a HomeKit issue, but reflects how a normal thermostat works.  Auto is the setting that allows for both Heating and Cooling - if you only have one enabled, you should probably delete Auto, and not implement the CoolingThresholdTemperature or HeatingThresholdTemperature Characteristics since they are only applicable for the Auto mode.

**Comment by HomeKidd** [comment]
```
10:11:39.285 ->               "iid":14,
10:11:39.285 ->               "type":"D",
10:11:39.315 ->               "value":24,
10:11:39.315 ->               "format":"float",
10:11:39.315 ->               "minValue":18,
10:11:39.315 ->               "maxValue":32,
10:11:39.315 ->               "minStep":1,
10:11:39.315 ->               "perms":[
10:11:39.315 ->                 "pr",
10:11:39.315 ->                 "pw",
10:11:39.315 ->                 "ev"
10:11:39.315 ->               ]
10:11:39.315 ->             },
10:11:39.315 ->             {
10:11:39.315 ->               "iid":15,
10:11:39.315 ->               "type":"12",
10:11:39.315 ->               "value":26,
10:11:39.315 ->               "format":"float",
10:11:39.351 ->               "minValue":18,
10:11:39.351 ->               "maxValue":32,
10:11:39.351 ->               "minStep":1,
10:11:39.351 ->               "perms":[
10:11:39.351 ->                 "pr",
10:11:39.351 ->                 "pw",
10:11:39.351 ->                 "ev",
10:11:39.351 ->                 "hd"
10:11:39.351 ->               ]
10:11:39.351 ->             },
```


```
10:11:39.252 ->               ]
10:11:39.252 ->             },
10:11:39.252 ->             {
10:11:39.252 ->               "iid":12,
10:11:39.252 ->               "type":"B1",
10:11:39.252 ->               "value":0,
10:11:39.252 ->               "format":"uint8",
10:11:39.252 ->               "valid-values":[
10:11:39.252 ->                 0,
10:11:39.252 ->                 1,
10:11:39.252 ->                 3
10:11:39.252 ->               ],
10:11:39.252 ->               "perms":[
10:11:39.252 ->                 "pr",
10:11:39.252 ->                 "ev"
10:11:39.252 ->               ]
10:11:39.252 ->             },
10:11:39.252 ->             {
10:11:39.252 ->               "iid":13,
10:11:39.285 ->               "type":"B2",
10:11:39.285 ->               "value":2,
10:11:39.285 ->               "format":"uint8",
10:11:39.285 ->               "valid-values":[
10:11:39.285 ->                 0,
10:11:39.285 ->                 2
10:11:39.285 ->               ],
10:11:39.285 ->               "perms":[
10:11:39.285 ->                 "pr",
10:11:39.285 ->                 "pw",
10:11:39.285 ->                 "ev"
10:11:39.285 ->               ]
10:11:39.285 ->             },
```

Everything looks okay at HomeSpan side 😄 


> However, one thing to check: above you mentioned you only wanted Cooling, not Heating. I just realized that Auto only makes sense if you have both Cooling and Heating enabled. This is not a HomeKit issue, but reflects how a normal thermostat works. Auto is the setting that allows for both Heating and Cooling - if you only have one enabled, you should probably delete Auto, and not implement the CoolingThresholdTemperature or HeatingThresholdTemperature Characteristics since they are only applicable for the Auto mode.

That was the problem actually, but i've solved it. First I've removed the `HeatingThresholdTemperature` (with Perms HD), but since Auto mode needs it too for setting the temp range that caused some Home app some issues. I was able to make an AC with only Cool/Auto mode, but it needs `HeatingThresholdTemperature`.  Most ACs have Auto Mode locked to one specific temperature (mostly 25,23 celsius) so what i've did is updated the Threshold values with Auto_temp +/- 1 celsius 😄 

But still something not OK with the Home app sometimes, If i make changes in some cases it takes too much time (even after ESP32 reboot, Home app re-open) to the changes to make effect. 
_E.g.: I'm decoding the AC remote protocol and setting min, max temp range based on that AC protocol, then later changing it to other AC protocol which has different min/max temp range sometimes take too many Home app re-opens to take effect and only thing is changed is basically setting range from 16-30 celsius to 12-32 celsius_ 

Since HomeSpan sending out the correct values it can be a Home related bug, issue. So closing this issue Thanks for your help again 😄
