### ISSUE TITLE
Pairing issue when using DHT library after recent update

### ISSUE THREAD

**Issue by mathew3811** [HomeSpan/HomeSpan#614]
"Unable to add accessory
Accessory discovery failed" shown when pairing.

Please try Leon676/HomeSpan-DHT22 for further diagnosis

**Comment by HomeSpan** [comment]
What did you update from and to?  Also, can you confirm that Example 1 is/is not throwing the same error?

**Comment by HomeKidd** [comment]
@mathew3811 

At [DEV_Sensors.h, line 25](https://github.com/leon676/HomeSpan-DHT22/blob/e4790dcab668bb6e833d2b4d7d0e1290c97296ef/DEV_Sensors.h#L25) the base value for Temperature is set to -10 **before** setting the range from 0-100 to -50 to 100. This causes setting an invalid _(out of range)_ value for temperature and it might causes the problem. I've got this unable to add accessory many time due to this minor thing.

Simply change this line from this : 
`temp = new Characteristic::CurrentTemperature(-10.0);`
...to this : 
`temp = new Characteristic::CurrentTemperature();`

**Comment by mathew3811** [comment]
@HomeKidd arghhh that is it! Spent countless hours trying to figure out where it went wrong. Though, somehow the sketch did actually worked literally a month ago and I haven't change anything since then. Still not sure how it happened.

I am really, really sorry @HomeSpan for blaming it on the update.

**Comment by HomeSpan** [comment]
I'm glad to hear it's working but I'm not sure why.  There IS error checking for out-of-range values - error messages appear on the Serial monitor both when you first launch HomeSpan as well as whenever you call setVal().  Also, setting the range directly after setting its value in `new Characteristic()` as done in the sketch is fine since both commands will be processed before HomeKit asks for any data.  You can see this by typing 'd' into the CLI.  Also, if you comment out the setRange() call you will see that HomeSpan generates an error.

One possibility is that the problem is someone intertwined with the use of the DHT library (Adafruit does not sell these anymore because the one-wire protocol is very problematic).  The sketch you referenced is almost of a clone of the Service Loops Example, which I was able to test and verify that pairing works fine (i.e. the range is properly communicated to HomeKit).  But I'd like to test the exact DHT sketch you are using.  Can you tell me which DHT library you have installed so I can download the same?

**Comment by OZ1SMB** [comment]
I have the same problem as mathew3811.

Some time ago I built a temperature sensor DHT21/Light switch combo, and it works well.
But now I built one more using the same schematics, code, files etc.
Then I get the same problem as mathew3811.
When I exclude all code regarding the sensors, there is no pairing problems.
I tried another code using DS18B20, same problem.

I also downloaded Leon676/HomeSpan-DHT22 but the same problem with pairing.

I also tried the solution HomeKidd suggested, but It did now work for me.

It's when I include anything with temperature sensors, I can't pair with HomeKit.

Any suggestions?

**Comment by HomeSpan** [comment]
Do you get any warnings in the Serial Monitor either when booting or at any time while running?

**Comment by OZ1SMB** [comment]
E (238) psram: PSRAM ID read error: 0xffffffff

**Comment by HomeSpan** [comment]
Try disabling PSRAM from the Arduino memory and recompile.  

But does everything else seems fine?  You get all the normal HomeSpan messages, connections to WiFi, pairing messages, etc.

**Comment by HomeSpan** [comment]
Type 'H' into the Serial Monitor to erase any previous pairing info.  Then when the system reboots, type 'L2' into the Serial Monitor to set the log level to verbose. 

Try pairing again - you should get a lot of output.  Copy everything on the Serial Monitor from the reboot until the pairing fails and post here - I'll see if I can figure out the issue based on the logs.

**Comment by HomeSpan** [comment]
If you look at the diagnostics coming from your sensor, it looks like the values are all `nan`.  This is being sent to HomeKit - if you inspect the log file above you can see:

`{"iid":9,"type":"11","value":nan,"format":"float","minValue":-40,"maxValue":80,"perms":["pr","ev"]}`

Since `nan` is not a valid value, the Home App refuses to acknowledge the pairing even though HomeSpan thinks it is paired (which is why you need to type 'H' if you want to pair again).

Ideally HomeSpan would have warned that you were sending `nan` values, which are out of range.  However, the way I wrote the check is to see if something is out-of-range, in which case I would raise a warning.  But comparing `nan` to any number fails, so `nan` is actually NOT less than -40, nor greater than 80, so, ironically, the check passes.  I'll address the warning error in a future release, but for now the issue is you are sending `nan` values instead of real numbers.

If this is new hardware, my guess is the sensor is not wired correctly and is not being detected, resulting in your library returning `nan` for all the values as shown in the last line of the log file.

**Comment by OZ1SMB** [comment]
Thanks many times for your help, It works now!
The error was on the breadboard, again thanks for you spending your time helping me.
