### ISSUE TITLE
Can't enter interactive mode.

### ISSUE THREAD

**Issue by iamxiaojianzheng** [HomeSpan/HomeSpan#639]
Can't enter interactive mode.

How should I troubleshoot the problem?

**Comment by iamxiaojianzheng** [comment]
When I used HomeSpan for the first time and compiled and executed it, it was possible to perform interactive operations. 

But I don't know why, after I recompiled later, I couldn't perform interactive operations. What exactly caused it, I don't know.

**Comment by HomeSpan** [comment]
What serial monitor are you using?  From within the Arduino IDE?  Check that the baud settings match what you used in your sketch, and also that you have new-line enabled.   As a baseline, always re-try Example 1 whenever there is an issues to make sure that there is not anything in your sketch that is causing the problem.

**Comment by iamxiaojianzheng** [comment]
> What serial monitor are you using? From within the Arduino IDE? Check that the baud settings match what you used in your sketch, and also that you have new-line enabled. As a baseline, always re-try Example 1 whenever there is an issues to make sure that there is not anything in your sketch that is causing the problem.

I use Anduino, the board is esp32s3. I have new-line enabled.

this is my code, and couldn't perform interactive operations in this code.

```ino
#include <WiFi.h>

#include "HomeSpan.h"

#define DATA_PIN 43

struct MyLED : Service::LightBulb {

  int ledPin;

  SpanCharacteristic *power;


  MyLED(int ledPin)
    : Service::LightBulb{} {

    power = new Characteristic::On();
    this->ledPin = ledPin;
    pinMode(ledPin, OUTPUT);
    digitalWrite(ledPin, HIGH);
    printf("Configuring On/Off LED: LedPin=%d\n", ledPin);
  }

  boolean update() {
    double val = power->getVal();
    double newVal = power->getNewVal();
    printf("Updating On/Off LED on pin=%d:  Current Power=%s  New Power=%s\n", ledPin, val ? "true" : "false", newVal ? "true" : "false");
    digitalWrite(ledPin, !power->getNewVal());
    return (true);
  }
};

void setup() {

  Serial.begin(115200);

  homeSpan.begin(Category::Bridges, "HomeSpan Bridge");

  homeSpan.deleteStoredValues();
  homeSpan.enableAutoStartAP();

  new SpanAccessory();
  new Service::AccessoryInformation();
  new Characteristic::Identify();

  new SpanAccessory();
  new Service::AccessoryInformation();
  new Characteristic::Identify();
  new Characteristic::Name("ESP32S3 LED");

  new MyLED(DATA_PIN);
}

void loop() {
  homeSpan.poll();
}
```

**Comment by HomeSpan** [comment]
In the above script you have enabled AP Auto Start.  This automatically causes HomeSpan to start a temporary Access Point allowing you to setup the WiFi, if you have not already setup WiFi on this chip.  During AP mode, all HomeSpan operations are halted - including the interactive use of the CLI.  Did you mean to start the AP upon boot up?

**Comment by iamxiaojianzheng** [comment]
I want to dynamically configure WiFi through the AP mode, instead of writing it in the code. 

Can I assume that if AP mode is enabled, I cannot enter CLI mode?

**Comment by HomeSpan** [comment]
Once AP is started, CLI stops until AP mode is completed.  This allows you to use your web  browser to connect directly to the ESP and enter your WIFI credentials.  Once you've done so, AP mode is terminated, the credentials you entered are saved, and the ESP32 reboots.  Upon reboot HomeSpan finds the WIFI credentials and does not bother starting the AP mode.

**Comment by HomeSpan** [comment]
One other thing - AP mode is only ONE way of dynamically setting your WIFI credentials.  The other way is to simply type 'W' into the CLI and don't use the AP at all.  Your should use one method or the others - not both. 

The thirds alternative is to hardcode your WIFI credentials into the sketch using the appropriate homeSpan commands, but this is not recommended.

**Comment by iamxiaojianzheng** [comment]
I would like to ask how do you solve the power supply of the board?

**Comment by iamxiaojianzheng** [comment]
In addition, I would also like to ask how do you solve the battery life problem? Please forgive me for so many questions.

**Comment by HomeSpan** [comment]
You cannot operate HomeSpan directly with a battery.  WiFi draws to much power, and HomeKit requires a constant WiFi connection -- you cannot put the ESP32 into a deep sleep mode since this will terminate the WiFi connection and cause HomeKit to show "No Response".

There are two solutions to this.  The first is to connect to HomeKit using BLE instead of WiFi.  Though HomeKit supports this, and some commercial devices use BLE, HomeSpan does not support BLE - only WiFi (no plans to add BLE).

The second solution is to create a HomeKit "hub" that is connected to WiFi and powered via mains (not battery), and a second "remote" device that is powered by battery, communicates with the "hub" using a low-power method, and can be placed in sleep mode when not used (such as between sensor readings).  HomeSpan has an entire protocol to do exactly this.  Please see the [SpanPoint](https://github.com/HomeSpan/HomeSpan/blob/master/docs/NOW.md) page and all the details and examples provided.

Also, please open new threads under the Discussion section of HomeSpan for questions, as opposed to issues, so the issues can be closed out when completed (and others can search and benefit from the questions).
