### ISSUE TITLE
Enhancement Suggestion for Status LED Functionality

### ISSUE THREAD

**Issue by maisyk** [HomeSpan/HomeSpan#641]
Hey, I would like to propose a constructive enhancement for the status LED functionality within the project. Currently, the status LED operates as a dedicated indicator, however, I have come across a design approach adopted by some products in the market that might be worth considering.

In certain instances, rather than employing a separate dedicated LED to convey the system's status, some products integrate the main light source itself as the indicator. For example, a lamp controlled by a relay could utilize the same pin for both the relay and the status indication. While this approach does offer advantages, it is noteworthy that the current rapid switching of the status light can lead to unintended consequences, such as potential relay lockup and subsequent ESP reboot.

In light of this, I propose the incorporation of a new function that would grant us the capability to customize the feedback displayed by the status LED for different operational modes. This feature could encompass the ability to modify flash patterns and intervals, providing greater flexibility in tailoring the indicator behavior to specific use cases.

I believe that this enhancement could contribute positively to the project's functionality and user experience. I would welcome the opportunity to discuss this suggestion further and provide any additional insights that may assist in its evaluation and potential implementation.

Thank you for your time and consideration.

Maisy

**Comment by HomeSpan** [comment]
This is a good suggestion, but if I'm understanding correctly, HomeSpan already provides everything you need.  See `setStatusCallback(void (*func)(HS_STATUS status))` on the [API page](https://github.com/HomeSpan/HomeSpan/blob/master/docs/Reference.md).  This function allows you to receive an alert whenever HomeSpan status changes.  You can then add your own code to perform any action - blink a status LED, display a message on an OLED, or change the color of the actual light controlled by HomeSpan.  These callbacks can be used in conjunction with, or instead of, the built-in status LED logic.

**Comment by HomeSpan** [comment]
Do you have any outstanding questions on this, or can I close?

**Comment by maisyk** [comment]
Hey, apologies for the very late response. I totally missed this one. But yes thank you my question has indeed been answered you are free to go ahead and close this :) 

Thanks, 
Maisy
