### ISSUE TITLE
Questions regarding pairing code setup and update of button pressed on the home app after "not response" or the ESP32 being offline and then online

### ISSUE THREAD

**Issue by willow2ko** [HomeSpan/HomeSpan#642]
First question : After setting the WIFI, is there a way to skip modifying the Setup Code? so it retains the one I set on Main file?

Second question: If my ESP32 is turned off while one of my services is on, how can I do to get that last state of my service once the ESP32 is back on? 

Thanks for your help :)

**Comment by HomeSpan** [comment]
If you set the WiFi Credentials and Setup Code from the CLI, the commands are distinct ("W" and "S") so they can be set independently.  If you use the HomeSpan Access Point, after configuring your WiFi Credentials you have the *option* of also changing the Setup Code.  Simply leave that input blank to retain the existing Setup Code.  A third option is to hardcode the Setup Code into your sketch, which is not really recommended, but still possible.

Re your second question, HomeSpan can automatically retain the state of Characteristics in NVS so they can be restored after a reboot/power-cycle.  The is done by setting an optional second parameter of the SpanCharacteristic constructor to "true."  See the API for complete details, as well as [Tutorial Example 18](https://github.com/HomeSpan/HomeSpan/blob/master/examples/18-SavingStatus/18-SavingStatus.ino).  Note that if you do retain the value of certain Characteristics (e.g. the "On" Characteristic for a LightBulb) you'll need to add some logic to the constructor for your LightBulb Service that uses this information in some way, such as by automatically turning on the light in the constructor itself, instead of waiting for the user to turn it own via the Home App.

**Comment by willow2ko** [comment]
Hi thanks,

Second question already solved with the piece of information you gave me. 

But for the first question: What if I actually want to hardcode my setup code on my sketch so no one can change it after the wifi setup? Lets ignore the access to the CLI, the way I built the PCB makes it not possible to access it.

**Comment by HomeSpan** [comment]
Hardcoding the Setup Code by placing `homeSpan.setPairingCode()` in your sketch overwrites any previously-saved Setup Code.  If a user updates the Setup Code via the HomeSpan Access Point after entering WiFi Credentials, the value they saved will be overwritten to the value you specified as soon as the sketch reboots after the Access Point is terminated.  In sum, they won't be able to change the code once you hard-code it into the sketch.

That said, I'll probably add a flag to the Access Point allowing you to disable to option to change the Setup Code to make sure the user does not even try to do so (even though it will have no effect).

**Comment by willow2ko** [comment]
How do you add a flag to the access point?

**Comment by HomeSpan** [comment]
Sorry, I meant that in a future release I will consider adding a flag.  This does not exist in the current version of HomeSpan. But regardless, even without such a flag, the user will not be able to change the Setup code in the AP if you hardcode the Setup Code in the sketch.

**Comment by willow2ko** [comment]
Thanks again for your great help and sorry for my confusion.

**Comment by willow2ko** [comment]
Quick question: What about setApFunction() ?

**Comment by HomeSpan** [comment]
As detailed in the API Documentation, it allows you *completely* replace the HomeSpan Access Point code with your own code.  That code can represent a different type of Access Point, or something completely different (like a touch interface on your device that requests the user to type in their WiFi Credentials).  In principle you can copy the entire existing Access Point code in the library, make changes, and then create your own custom AP.

**Comment by willow2ko** [comment]
I guess I'll just wait for your next release.

Thanks :)
