### ISSUE TITLE
Service::InputSources on Service::Television stopped working in iOS 17

### ISSUE THREAD

**Issue by FWeinb** [HomeSpan/HomeSpan#648]
After updating to iOS 17 the Home app is not showing the list of configured InputSources anymore, neither in the switcher nor in the configuration. Everything else is working as expected though. I could even reproduced this behaviour with the example provided in this repository. I am using the release version 1.8.0 in all my projects.

**Comment by HomeSpan** [comment]
Hopefully this will be addressed in the production version of iOS17.  Do you know if this effects commercial devices as well?

**Comment by mLihs** [comment]
Works fine - only issue I do have is that the list of inputs isn't in order its Radom …

**Comment by HomeSpan** [comment]
Thanks for the update.  Not sure how to address the issue of the list of inputs being in random order.  This may be an apple problem.

**Comment by silabs-AttilaB** [comment]
@mLihs What iOS version do you use? Does your Remote Switch app work correctly? Since I updated to iOS 17 the Remote Switch app stopped working properly:
![41dd2c59-be63-4b25-8d56-b809cf2cdcb4](https://github.com/HomeSpan/HomeSpan/assets/67368926/b050e6e9-86a4-4c8d-8bb7-b79c6577a535)

**Comment by atban98** [comment]
@mLihs What iOS version do you use? Does your remote switch app work correctly? Mine got stopped working properly after I updated to iOS 17 last year:
![41dd2c59-be63-4b25-8d56-b809cf2cdcb4](https://github.com/HomeSpan/HomeSpan/assets/62559545/600745a4-c971-4c41-bcd3-0118efab293c)

**Comment by HomeSpan** [comment]
I'm on iOS 17.3.1 and can confirm the remote control app is not working correctly - neither with HomeSpan nor my Sony TV that has HomeKit built in.  Both TVs work fine when using the Home App, but the remote control app is messed up.  The volume buttons do not work, the power button does not work, and the play/pause button seems to turn the TV power on instead.  Same things happens for both my commercial and HomeSpan-controlled TV.

The previous remote control app (I guess I have not checked since iOS 16) worked fine with both TVs, including the volume controls.  Seems like Apple made some changes in the remote app that are inconsistent with even the specs used by commercial devices.  Not sure this will be possible to debug, especially since Apple provides no specs for this.
