### ISSUE TITLE
RGB neopixel limited to 255?

### ISSUE THREAD

**Issue by pjphel** [HomeSpan/HomeSpan#654]
I am using a RGB neopixel strand and can only get 255 of the 300 pixels to work.  if I set the number to 300, only 44 light up.  any ideas?

**Comment by HomeSpan** [comment]
This is a problem with the example sketch. I used `uint8_t nPixels` everywhere instead of `int nPixels`.  The HomeSpan library uses `int` so it can handle more than 255 pixels.  All you need to do is change all instances of `uint8_t nPixels` to `int nPixels` in the example and it should work fine for strands greater than 255 pixels.  I've updated the example --- will be fixed in the next release.

**Comment by pjphel** [comment]
Awesome, thanks!  The library is amazing, appreciate you.
