### ISSUE TITLE
DRV8825 driver for automated blinds

### ISSUE THREAD

**Issue by Julius-Bendt** [HomeSpan/HomeSpan#683]
Hello!

I couldn't really find any information if a Stepper class for the DRV8825 driver have already been made.
That made me wonder; could I use the AccelStepper library, inside a custom build stepper class and expect it to work with homespan?
Or, would a better approch be to create the new stepper class from scratch?

**Comment by HomeSpan** [comment]
This driver seems very similar to the A3967 example already in HomeSpan with the exception that the 8825 uses 3 pins to configure up to 8 modes whereas the A3967 uses 2 pins to configure 4 modes.  Otherwise they both use a pin for DIR and a pin for STEP.  Would suggest you modify the A3967 implementation (by adding a third mode pin) and use the HomeSpan Stepper Library.

**Comment by HomeSpan** [comment]
@Julius-Bendt, anything to update on this, or can I close?

**Comment by Julius-Bendt** [comment]
I havent had a chance to take a look at it yet. I'll close the issue, and open it again when I have some updates.
Thanks for the advise, I'll look in to it and share the code whenever I have the time :D
