### ISSUE TITLE
Accessory not detected

### ISSUE THREAD

**Issue by ciananDR** [HomeSpan/HomeSpan#690]
I had initially paired to the accessory then I removed it, now when I try to scan to pair it will not appear.
Is there a way to reset the homekit storage?
Or is there a function i can use to solve this problem?
Thanks

**Comment by HomeSpan** [comment]
If you unpair the Accessory from the Home App, and HomeSpan is running, it will automatically unpair as well.  If you unpair the Accessory from the Home App, and HomeSpan is NOT running (e.g. the ESP32 device is not powered, not connected to WiFi, etc.) then HomeSpan will still think it is paired.

To force HomeSpan to think it is unpaired, type 'U' into the Serial Monitor (or type '?' to see all the options).  You should now be able to re-pair the device with the Home App.  Note that if you type 'U' in HomeSpan instead of unpairing  in the Home App, you'll have the reverse problem - HomeSpan will think the device is unpaired, but the Home App will still think it is paired.  So you'll still need to go into the Home App and unpair the device.

All of the above assumes you did not make ANY changes to the HomeSpan configuration, such as changing the definitions of any Accessories, Services, or Characteristics.  If you did, there is a high likelihood that when you try to repair the Home App  will be confused since it sees the same device but with a new configuration.  To solve this, type 'H' instead of 'U' in to the Serial Monitor.  This not only forces HomeSpan to delete all pairing info, but it also regenerates a completely new Device ID, which means the Home App will see the ESP32 as a completely new device totally unrelated to the whatever you had previously paired.

When developing sketches with lots of changes, I often need to unpair from the Home App, type 'H', and then re-pair.

**Comment by ciananDR** [comment]
Thank you!
Kind regards
Cianán
