### ISSUE TITLE
Servo class - is speed adjustable?

### ISSUE THREAD

**Issue by YouCanNotBeSerious** [HomeSpan/HomeSpan#707]
I'm having a hard time as I am not a real coder, just a hacker.... Can I specify the speed that the servo moves to the target, in the motorised blinds example?  When moving the slider, the servo moves very quickly to the new position i.e. as fast as it can!

It seems the bit I need is "update actual servo position"......

```
if(hTiltTarget->updated()){                         // check to see if shade tilt angle was updated
      hTiltCurrent->setVal(hTiltTarget->getNewVal());   // set current value of tilt to match target value
      hTiltServo->set(hTiltTarget->getNewVal());        // <--- update actual servo position with ServoPin->set(degrees) method
    }
```

but in PWMPin.h there's only 

```
class ServoPin : public LedC {
  uint16_t minMicros;
  uint16_t maxMicros;
  double minDegrees;
  double microsPerDegree;
```

I am new to OO programming so following along as best I can!

**Comment by HomeSpan** [comment]
The HomeSpan Servo class does not provide a method to set the speed of change (though it's a good idea and might be something I can add in the future).  However, you should be able to accomplish this by having your code only change the hTiltCurrent in small steps to approach hTiltTarget, rather than set it to match hTiltTarget all at once.

The easiest way to do this would be to manage the process from within the `loop()` method for the Service instead of within the `update()` method.  Within the `loop()` method you can compare the current and target states, and if different increment the current state a little towards the target state.  Since the `loop()` method gets called every cycle, this will very quickly cause the current state to match the target state.  To slow things down you can use the `timeVal()` method for the current state and check to see whether a few seconds have elapsed since the last change.  If not, don't update current state.  If so, update it to approach target state.  By judicious choice of the increment by which you update current state, in combination with whatever `timeVal()` period you choose, you should be able to fine tune the speed of the Servo update.

**Comment by YouCanNotBeSerious** [comment]
>However, you should be able to accomplish this by having your code only change the hTiltCurrent in small steps to approach hTiltTarget, rather than set it to match hTiltTarget all at once.

Thanks for the timely reply, I have been trying this today actually - in the update() method.

It works.....with jerkiness and other problems that i suspect are because things are changing value while i am using delay() inside the update() method.  In other words, just what you have pre-emptively said :-)

Will move it to the main loop and use the presumbaly non blocking timeVal() route, thanks!
