### ISSUE TITLE
ESP8266 ESPNOW receiving from homespan spanpoint example

### ISSUE THREAD

**Issue by Fedaasalem** [HomeSpan/HomeSpan#719]
please when I tried to make ESP8266 as a ESPNOW receiver from ESP32 spanpoint , the ESP32 print a message that the message is sent successfully but nothing is received on ESP8266. so please if there is an example to show how to configure ESP32 as a homespan spanpoint sender and ESP8266 as a receiver , please share. my project is to make ESP32 as a server to send commands to all ESP01 relay modules to control home lighting system.

**Comment by Fedaasalem** [comment]
Is there anyone can help ?

**Comment by thncode** [comment]
I do have the same problem - any solution yet???

**Comment by HomeSpan** [comment]
I'll review over the next week or so and post an example.

**Comment by HomeSpan** [comment]
Please see this new [SpanPointLightSwitch Repository](https://github.com/HomeSpan/SpanPointLightSwitch) for a series of example sketches that shows how to both send data to, and receive data from, remote ESP32 and ESP8266 devices.

In this example I created a HomeKit sketch that implements two simple on/off LightBulb Accessories.  The sketch is similar Tutorial Example 5, except that instead of controlling two LEDs connected to pins on the device, the sketch transmits on/off instructions to a remote ESP32 and remote ESP8266 device.  These devices each have an LED attached and will turn it on/off in response to messages received from the main device.  The code is mostly annotated, but you'll need to reference the HomeSpan SpanPoint page to fully understand all the parameters.

Enjoy!

**Comment by Fedaasalem** [comment]
Thanks it works
