### ISSUE TITLE
Where does "fault" value appear?

### ISSUE THREAD

**Issue by YouCanNotBeSerious** [HomeSpan/HomeSpan#726]
I am somewhat successfully modifying the example remote temperature sensor code (SpanPoint) but in the main device code, I don't understand the "fault" mechanism.... can anyone enlighten me?

```
 if(remoteTemp->get(&temperature)){      // if there is data from the remote sensor
      temp->setVal(temperature);            // update temperature
      fault->setVal(0);                     // clear fault
```

Where does the "fault" (StatusFault) characteristic appear for the end user?  I can't see anything in Home.app or a third party one like Eve ....

Thanks!

**Comment by frankonski** [comment]
When it comes to SecuritySystem, using `Characteristic::StatusFault` does not provide any indication of a fault in the Apple Home app. But when using Eve, the icon shows up as a red exclamation mark saying there is a "General Fault - The accessory reports fault code 1. Please refer to its user manual".

Since HAP only support 1 or 0 for status code, there is unfortunately no way to display any other fault code than 1. :(

**Comment by YouCanNotBeSerious** [comment]
Thanks - will re-test with Eve, maybe I missed the icon since I need things to be as subtle as a sledgehammer :-)

**Comment by YouCanNotBeSerious** [comment]
.
