### ISSUE TITLE
Connected to WiFi, but won't acknowledge it.

### ISSUE THREAD

**Issue by cgarland26** [HomeSpan/HomeSpan#734]
I have a unique WiFi connection because it is a school WiFi (WPA2-Enterprise), so it doesn't seem like the HomeSpan library has the capability to connect to it. In order to get around this, I used a different method to connect to the WiFi, but HomeSpan won't try to use this connection because it is stopped by, "No WiFi credentials found". Is there a way to try and bypass this and get HomeSpan to try and work anyways? Here is the code that I got to connect to the WiFi, and was successfully able to make get requests. (I don't how to get it to look fancy)

#include <WiFi.h>
#include <esp_wpa2.h>
#include <esp_wifi.h>

const char *ssid = "wifi";
#define EAP_IDENTITY "username"
#define EAP_PASSWORD "password"

int status = WL_IDLE_STATUS;

void setup()
{
  Serial.begin(9600);
  
  WiFi.disconnect(true);
  WiFi.mode(WIFI_STA);
  esp_wifi_sta_wpa2_ent_set_identity((uint8_t *)EAP_IDENTITY, strlen(EAP_IDENTITY));
  esp_wifi_sta_wpa2_ent_set_username((uint8_t *)EAP_IDENTITY, strlen(EAP_IDENTITY));
  esp_wifi_sta_wpa2_ent_set_password((uint8_t *)EAP_PASSWORD, strlen(EAP_PASSWORD));

  esp_wifi_sta_wpa2_ent_enable();

  while ( WiFi.status() != WL_CONNECTED) {  
    WiFi.begin(ssid);

    // wait 10 seconds for connection:
    delay(10000);
  }

  // print your WiFi shield's IP address:
  Serial.print("IP Address: ");
  Serial.println(WiFi.localIP());

}

**Comment by HomeSpan** [comment]
Sorry, HomeSpan does not presently support WPA-Enterprise.  It's not obvious that HomeKit will work when connected to that type of network, since the router may not permit certain protocols (or it may - hard to know without testing).

As a potential work around (though I have no idea if this will work), you can try adding your code above to the beginning of the sketch to establish a WiFi connection before anything else.  Then, use `homeSpan.setWifiCredentials(const char *ssid, const char *pwd);` to force HomeSpan to think there are credentials, even though they won't be used.

**Comment by cgarland26** [comment]
That worked perfectly. Thank you!
