### ISSUE TITLE
Cannot access weblog webserver on iphone

### ISSUE THREAD

**Issue by sevmamba** [HomeSpan/HomeSpan#742]
Hi, thanks for Homespan, great job. 

As per your github website, if I put http://homespan-8e312df8ac2e.local:80/myLog into my browser on WINDOWS, I do see the webpage, great, fantastic.

BUT it fails on the iphone, I get a blank screen. I've used the Safari app, the DuckDuckGo app and the Chrome app none of them will display the webserver page.

I really don't think this is a bug with Homespan, but I've spent many hours googling  this and cannot find a solution, can you offer any help,
Thanks, Sev

**Comment by HomeSpan** [comment]
Can you verify that your phone is on the same WIFI network as the HomeSpan device (the device can *only*  be reached from within your local home network).  Also, if your router supports both 2.4 GHz and 5.0 GHz WiFi, you need to have it configured so that traffic between the two networks is allowed and seamless.  This is because the ESP32 will only connect to 2.4 GHz and your iPhone will likely connect to 5 GHz if available.

**Comment by sevmamba** [comment]
Yes on the same network etc, but I found the problem, at the righthand end of the url which is myLog, I had typed mylog without the capital L,, when I type the capital L it works, I did not now the url is case dependant. I've tested it on two iphone and the same result.
Just for info, my Windows laptop connects to the network via a 5ghz access point and displays correctly, and I've just tested that my iphone too can connect to the webpage (now I type the capital L) on both 2.4 and 5GHz. 

Please mark this as closed, and thank you for your prompt reply,
