### ISSUE TITLE
Were you ever able to add Adaptive Lighting?

### ISSUE THREAD

**Issue by majortom64** [HomeSpan/HomeSpan#748]
I am not sure if Apple ever documented it, but it is an important feature for LED bulbs and strips.

Thanks!

**Comment by HomeSpan** [comment]
Sorry, but I can't find anything that describes how this works.  At a minimum I would need the UUIDs of the Characteristics, their expected formats, and how they operate.

Apple seems to have locked down all specs for HomeKit a while ago - even the current Apple developers site does not show any Services added over the last few years, such as a Television.  Since these Services obviously exist, I presume they are all documented in Apple's commercial HAP specs, but Apple only provides this under NDA to qualified manufacturers (i.e., not individual hobbyists).

**Comment by majortom64** [comment]
This seems to have support for adaptive lighting written in Javascript. Not sure if this would help. :-)

**Comment by majortom64** [comment]
Were you able to look at that example?

**Comment by HomeSpan** [comment]
Yes, I reviewed a few times but unfortunately I was not able to decipher the required UUIDs and method.  I looked for a source on the Web and Apple itself is completely silent.

**Comment by nbelles** [comment]
I consulted the sands a little bit and it was able to generate a fully working example based on the reverse engineering done in [homebridge/HAP-NodeJS](https://github.com/homebridge/HAP-NodeJS)'s [AdaptiveLightingController](https://github.com/homebridge/HAP-NodeJS/blob/master/src/lib/controller/AdaptiveLightingController.ts). I tested this on my ESP32C6 and it successfully showed up as an Adaptive Lighting enabled light and controlled the color temperature and brightness correctly. I then had it clean up all the code into proper changes on the base HomeSpan repo. Here's a PR with all the changes: https://github.com/HomeSpan/HomeSpan/pull/1163 

I don't intend it to be ready to merge as-is, there's probably a lot of work to do to make it fully ready to merge. I more-so just wanted to post it so that anyone needing help would have some examples and documentation to work from and if the maintainer(s) of this repo want to clean it up and make it ready to merge then they can do that. Hope it helps!
