### ISSUE TITLE
ESP32-H2 - Thread/Matter Support? (feature/enhancement)

### ISSUE THREAD

**Issue by hanzov69** [HomeSpan/HomeSpan#749]
Now that the ESP32-H2 devboards are broadly available, will there be any work done to support Thread/Matter in Homespan?

**Comment by HomeSpan** [comment]
HomeSpan uses the Arduino-ESP32 core, which has not yet been updated to use version 5 of the Espressif IDF that contains support for Thread and Matter.  The current production core uses IDF 4.4 (https://github.com/espressif/arduino-esp32#arduino-core-for-esp32-wifi-chip).   Once Espressif releases their new version 3 of the Arduino-ESP32 core into production I'll start investigating support for Matter and Thread, though initially I believe there will be lot work to do just to address anticipated breaking changes in version 3 of the Arduino-ESP32 core.

**Comment by hanzov69** [comment]
@HomeSpan thanks for the info, greatly appreciated.

**Comment by aberlanga-gatech** [comment]
Hi--sorry to revive an old thread but I wanted to ask if there have been any updates for Thread/Matter support for Homespan? The Arduino-ESP32 core has been updated with significant OpenThread functionality as of 3.1.0 rc (released yesterday I believe). Really excited to use the reliability Thread with the intuitiveness of Homespan!!

**Comment by HomeSpan** [comment]
HomeSpan 2.0.0-rc.1 has been released.  This version supports version 3 of the Arduino-IDF Board Manager.  However, there are no plans at present to add anything related to Matter.  With regard to just Thread, I'm not sure there is a way to use it for connectivity directly to HomeKit (via a HomePod) since that seems to be only for Matter.  But there may be other uses for Thread, such as a complement to using ESP-NOW for SpanPoint.  Will explore that in the future, but for now HomeSpan will not be more generally implementing any Matter/Thread protocols.

**Comment by aberlanga-gatech** [comment]
Hi—thanks for the update! I’ve downloaded it, and it looks fantastic!

Regarding Matter, I totally understand the decision not to pursue it further, since HomeSpan is already optimized for HomeKit and its HAP implementation.

As for Thread--I thought  HAP itself is agnostic to the transport layer and is meant to work over multiple protocols (BLE, WiFi, and Thread). For instance, Eve products use Thread with a HomePod Mini acting as a Thread Border Router. From what I understand, the key difference between WiFi and Thread communication is mainly at the physical layer (since Thread uses IEEE 802.15.4). Both use mDNS for service discovery, so the higher-layer communication and pairing mechanisms should theoretically stay the same.

Given that HomeSpan already supports mDNS, could it be that some modifications could be made to handle the lower-level Thread networking stack and routing? 

My reasoning/assumption is that implementing HomeSpan over Thread would primarily involve coding functionality to enable device pairing through Thread. This could potentially leverage the existing _hap_.udp service for communication, though I'm not too networking-savvy, so I'm not sure how that would look in practice.

Of course, there could be other constraints I’m unaware of, especially regarding Thread’s specific stack requirements. But if the existing HomeSpan code can be adapted to use a Thread radio instead of a WiFi interface, it might not be too much of a leap to get it working. I think that Thread support could bring huge benefits, especially in light-weighing home automation for low power consumption and network reliability (especially in places where there are a lot of devices like an office building).

Like I said--I am not a networking expert (far from it, believe me), but I am eager to learn! These are just some thoughts--HomeSpan is already an amazing tool as is!


sources: 
https://www.evehome.com/en-us/homepodmini
https://support.apple.com/en-us/102557#:~:text=Thread%2Dbased%20accessories%20require%20a,and%20control%20accessories%20while%20away.)

**Comment by HomeSpan** [comment]
I agree with your comments above.   The weak link in the HomeKit ecosystem is the reliance on MDNS over WiFi.  MDNS over Ethernet works fine, which is why many commercial devices use a central hub for connectivity to HomeKit.  I have well over 100 commercial HomeKit devices and all those that go through an Ethernet-based hub never have any issues.  Those that connect directly with WiFi suffer the same "No response" problems as sometimes reported with HomeSpan.

Ideally, one would be able to use a Home Pod as a Thread Border router and transparently connect to a home's WiFi network.  HomeSpan would continue to use HAP and HomeKit would not even know about the intermediate Thread Border Router.  However, I'm not sure a Home Pod can be used as a general Thread Border router, or whether Apple has it locked down so that it can only be accessed when using Matter.  I've not been able to find anything on the web about connecting directly to a Home Pod for use as a Thread Border router.

Even if that is not possible, it still might make sense to create a HomeSpan Hub that uses thread for device communication and Ethernet for HAP/HomeKit.  Sort of how SpanPoint uses ESP-NOW, but hopefully more robust.
