### ISSUE TITLE
esp switch goes abruptly unreachable 

### ISSUE THREAD

**Issue by AbulfaslAhmadi** [HomeSpan/HomeSpan#774]
The ESP functions flawlessly right after its init. It operates swiftly and responds promptly. However, after a brief period, the Apple Home app indicates that the device is unreachable, and the switch fails to control the light. Both the Apple device with the Home app, as well as the ESP device maintain a connection to the AP so none of them went offline. 

I initially implemented a script on my ESP to restart the entire program at intervals of a few minutes. However, this proved to be only a temporary fix. I've since switched to an alternative solution, which means I'm unable to provide logs at the moment. I'm unsure what I might be doing wrong.  If this issue is resolved in the future, I may reconsider reverting to the previous setup because I really enjoyed using it.

**Comment by HomeSpan** [comment]
Are you using a HomePod or Apple TV as a HomeKit Hub (Apple required this since iOS 16 or so)?  Also, are you getting a message in HomeKit that the device is "Not Responding" or does it actually say "Unreachable" (which I've not seen before).

One other thing to note is that the ESP32 device must be on the same network SSID as your iPhone/HomePod, etc.   If your router supports both 2.4 and 5.0 GHz WiFi, it must be configured to allow for seamless communication between the two.   And your router must also NOT filter any UDP messages or MDNS messages - some routers do this by default and have an option to disable.  Others do this without an option to disable.

**Comment by AbulfaslAhmadi** [comment]
I don't use a HomePod or Apple TV, because I use it only localy when I'm home. The HomePod or Apple TV is just needed for remote access - as far as I know. At least it actually did work for me (localy) without any Hub (even with iOS16). The ESP was after the init reachable and I could control it, but it lasted only for a few minutes until it went to "Not Responding". After a while, it became accessible again, but with a bigger delay. Unfortunately, it eventually reverted to showing as "Not Responding" once more. And that happend over and over again. All in all a really weird behaviour.

The "unreachable" message must be also then a bad translation from german. I use the app in german and just translated it into english (without knowing how it is called by apple with english as configured language).

I plan to investigate the aspects you mentioned, such as the 2.4GHz and 5GHz communication and my router settings regarding the UDP and mDNS protocols. However, I'm currently busy for the next few days, so it may take some time before I can troubleshoot the problem and respond here. Thanks for now :)

**Comment by AbulfaslAhmadi** [comment]
It works! I reflashed/reinstalled my Arduino IDE and the entire memory of the ESP at the beginning and it seems to work fine :)

Must have been a write error or something....

Thanks!
