### ISSUE TITLE
Issue with library update

### ISSUE THREAD

**Issue by iluky** [HomeSpan/HomeSpan#778]
I updated the library to the latest version and I am getting the following error:

`Error: The section .text exceeds the available space on the board.`

I was able to workaround the issue by downgrading the library to the previous version 1.8.0.

Is there anything I can do to fix the issue and get the same result as the previous version of the library?
![Screenshot 2024-02-19 alle 14 03 31](https://github.com/HomeSpan/HomeSpan/assets/9388241/bb7ac3b9-6a51-4a6d-97e2-a6afa5bdeb30)
![Screenshot 2024-02-19 alle 14 02 27](https://github.com/HomeSpan/HomeSpan/assets/9388241/f02b4dde-2087-44e1-9b21-9a4cfaee3bc3)

**Comment by HomeSpan** [comment]
Based on the screenshot above you are probably using the default partition scheme for the ESP32, which provides only 1.3MB of program space since it reserves a full 1.5MB for a SPIFFS partition.  This is wasted space since HomeSpan does not use SPIFFS at all.  If you compile your code with a partition scheme that reserves only a small amount of SPIFFS space, you'll free up extra 600MB for program storage (an increase of almost 50%).

In the Arduino IDE you simply choose your partition scheme from the Tools Menu of the IDE itself.  I'm not sure what IDE you are using above - if not the Arudino IDE, you'll need to check documentation for how to select a different partition scheme.

**Comment by iluky** [comment]
You're absolutely right! I switched to a different partition scheme in the Arduino IDE that allocated less space to SPIFFS, and voila, no more memory issues!
Thanks so much for your insightful analysis and solution. It saved me a ton of time and frustration.
