### ISSUE TITLE
enableOTA quit working?

### ISSUE THREAD

**Issue by TomInIowa** [HomeSpan/HomeSpan#797]
homeSpan.enableOTA("brenda");                   //default  homespan-ota  False .. no password

I ****love** homeSpan!!**   the OTA quit working for me.    The default "homespan-ota" is what works.

I am using version 1.7          I run out of space with 1.9

**Comment by HomeSpan** [comment]
It seems to be working on 1.9.0.  What is the exact error you are getting?

Note that when you call `enableOTA()` with a password (such as indicated above), this does not have any impact on the NEXT upload.  That's because the password you are specifying is NOT the password that the Arduino IDE will send to HomeSpan when uploading.  Rather, it's the password that the HomeSpan will use to cross-check against whatever password you type into the Arduino IDE.

For example, if you have enabled OTA but did not specify a password, HomeSpan will expect you type "homespan-ota" into the Arduino IDE whenever you use OTA.  If you change your sketch to say `homeSpan.enableOTA("brenda");` and then use OTA to upload, you will still need to use "homespan-ota" as the password since the sketch is not yet uploaded and HomeSpan has no idea that you want to change the password to "brenda."   But after you upload and the sketch restarts, HomeSpan will see the revised password, and the *next* time you try to upload, you will need to type "brenda" as the OTA password.

In sum, OTA password changes always take place after the next upload that contains the password change.

Regarding space, if you can't upload 1.9.0 (it's about 200K larger than 1.8.0), that's probably because you are not using all the Flash memory available on the ESP32.  The Arduino default reserves a lot of the flash space for use as a SPIFFS partition.  But this is wasted space since HomeSpan does not use SPIFFS.  To free up this space and increase the memory available for your sketch by 50%, see [here](https://github.com/HomeSpan/HomeSpan/blob/master/docs/Solutions.md#my-sketch-is-too-large-to-be-uploaded-error-when-trying-to-upload).

**Comment by wiltonleewf** [comment]
Hi, I encountered the same problem. Noticed if the upgrade moving from 1.8 to 1.9 via OTA will fail despite being authenticated successfully.  However, when the device is connected to USB, the upgrade went on successfully..

**Comment by HomeSpan** [comment]
Hmm.  Can you describe exactly what occurred.   Seems to be different from original post where authentication was failing.  Are you saying that when you updated from 1.8 to 1.9 that upload failed?  Or is that the upload of 1.9 went fine, but then the next time you tried to upload a change (with 1.9 already running on the chip), the authentication worked but the device did not actually update?

If the authentication works, and there are no interruptions in the transmission, the new sketch should have been loaded UNLESS you did not enable OTA in the new sketch.  HomeSpan has a built-in protection to make sure you enable OTA in any new sketch you upload via OTA.  If not, then upon reboot HomeSpan automatically reverts to the previous partition.

Also, if you change the partition scheme to something that does not contain an OTA partition, this will cause a fail.

**Comment by wiltonleewf** [comment]
Yes, if the ESP32 was last updated with 1.8 via OTA, and then using the upgraded 1.9 to perform the same OTA, will fail despite successfully authenticated. 

I have tried downgrading the Library for Homespan to 1.8 and redo OTA ensure it is successfully updated with the recommended minimal SPIFFs before upgrading H
![Capture](https://github.com/HomeSpan/HomeSpan/assets/20575363/8e7c8bc1-24ab-43d0-95cd-d96450607c29)
omespan to 1.9, but this was to no success as well. 

Attached is a screenshot of the failed attempt

**Comment by HomeSpan** [comment]
If you downgrade to 1.8 using USB, and you still get the error above, this suggests there may be something corrupted on the Flash memory.  Can you reload 1.8 again using USB, but *before* you do, set the "Erase All Flash Before Sketch Upload" to "Enabled" option in the Arduino IDE.  This will cause the entire flash to be reformatted (takes a bit longer to upload).

Than once rebooted, use the 'W' CLI command to re-input your WiFi Credentials.  Next, go back to the IDE and set the "Erase All Flash" back to "Disabled" and upload via USB once again.

If upon rebooting the WiFI data is still present (it should be), then switch to OTA and try uploading your sketch again (still using 1.8).

**Comment by wiltonleewf** [comment]
Hi, I did a physical connection to upgrade.. All is well and had to redo the WiFi setup and HomeKit pairing all over again after the upgrade.  Thanks

**Comment by HomeSpan** [comment]
Glad to hear it's working.  @TomInIowa, were you able to resolve as well?
