### ISSUE TITLE
Decrypted message error

### ISSUE THREAD

**Issue by Glujaz** [HomeSpan/HomeSpan#831]
Hi there, still doing some stuff on my side with the same amplifier project.

I wanted to mention an error message I see in the console. It's typically that kind :

*** ERROR:  Malformed HTTP request (Content-Length plus Body Length does not equal total number of bytes read)

or

*** ERROR:  Decrypted message of 1641 bytes exceeded maximum expected message length of 1042 bytes

This seems to happen mostly when I am looking on the state of the ESP32 in the home app of my iPhone (on the latest version of iPhone OS), and not when using the Mac version of the home app (on Sonoma)

For info, here is my code : https://github.com/Glujaz/Rotel-A12MKII-Homekit/blob/main/Rotel_Homespan.ino

**Comment by HomeSpan** [comment]
I have recently noticed this same error in my own setup a few times a few days ago.  I'd never seen HomeKit send a malformed message before, but that's what this means.  However, that only occurred a few times and then it stopped.  This could be a change on the HomeHub side, perhaps from a recent Apple update.  Will keep an eye out if it occurs again and try to identity the source.  However, it does not seem to be problematic since when it did occur, HomeKit quickly followed up with a properly formed message that HomeSpan was able to process.
