### ISSUE TITLE
Whenever I read brightness value, I get previous value instead of the current one somehow

### ISSUE THREAD

**Issue by AAfetisov** [HomeSpan/HomeSpan#834]
How to replicate:
make a brightness slider app for Light category.
tap somewhere at the top of the slider ( ~90%). Get some random value. Then tap at the bottom and get 90%.

Am I doing something wrong? Im new to the whole esp thing.  Phone's Home app gives same results

_the code is copied from 10-RGB-LED example_

https://github.com/HomeSpan/HomeSpan/assets/1430709/df1706c2-7409-4fff-b7b1-8faf8e0808c4

**Comment by HomeSpan** [comment]
Are you running a completely unmodified version of the example?

**Comment by HomeSpan** [comment]
Your code above is incorrect - you are using getVal instead of getNewVal, hence you are seeing the previous values not the updated values. 

Note that in Example 10 we use both getVal and getNewVal.  The use of getVal is simply for instructive purposes so you can see how the update proceeds.  The use of getNewVal is where the updated values are actually read and processed.

**Comment by AAfetisov** [comment]
> Your code above is incorrect - you are using getVal instead of getNewVal, hence you are seeing the previous values not the updated values.
> 
> Note that in Example 10 we use both getVal and getNewVal. The use of getVal is simply for instructive purposes so you can see how the update proceeds. The use of getNewVal is where the updated values are actually read and processed.

Oh thank you very much. I really tried everything except for that :) Also you did great job commenting everything. It really helps
