### ISSUE TITLE
Schedule Reboot

### ISSUE THREAD

**Issue by mathew3811** [HomeSpan/HomeSpan#853]
I have created a Homespan device for monitoring simple indoor conditions, temp, humidity, light level etc. From time to time one or more of the aforementioned data will get stuck and stop updating. (Esp32 is still connected, only the data not updating, weblog accessible) Whenever it happens I then have to manually power cycle the esp32 and the issue goes away.

I was wondering if there is a way to program a schedule reboot say every 24h so that it can resolve the issue on its own? Thanks

**Comment by maisyk** [comment]
Sounds like a memory leak to me but I could be wrong. You can try `ESP.restart()` or `abord()`. 

According to this [article](https://esp32.com/viewtopic.php?t=29658) `abort()` may give you better results.

You would have to add some additional logic of course to ensure it runs every 24 hours. 

Ideally you shouldn't go down this route but as a quick fix it should be fine until the source of the issue is found.

**Comment by HomeSpan** [comment]
If the device is working and responds to weblog requests, but shows no response in the Home App, this is very likely the result of an MDNS issue.  There are many threads on this problem across the web, including quite a number on the HomeSpan site itself.

Getting to the bottom of this issue has not been possible as it seems the root of the problem lies in the interaction between the MDNS library used by Espressif and the MDNS protocols used by SOME home WiFi routers.  Mesh routers can be particularly problematic when used with HomeKit.  In my own setup, I used the Velop mesh router for a number of years with no problem.  Then, after firmware updates to the Velop, I had constant MDNS drop-outs.  I switched to an Orbi mesh router a few years ago and have had absolutely no problems since then.

Rebooting the device every 24 hours is certainly one solution, assuming that your connection to the Home App usually stays up longer than 24 hours.  To do so, I would add a check in the main arduino loop that sees if `millis()` is greater than 8,6400,000, and if so, call ESP.restart() as suggested above.

However, you definitely want to check first that the problem is not related to something else in your sketch.  One common cause of losing connectivity with the Home App is sending out-of-range values.  For example, if you send a temperature less than 0, this will cause problems because the default range does not allow negatives.  To address, simply use `setRange()` in your sketch to expand the set of allowed values.

HomeSpan throws warnings whenever your sketch sets the value of a Characteristic outside its range, so you can check the Serial Monitor for such warnings to see if that is the source of the disconnect.
