### ISSUE TITLE
Incorrect behaviour of windowcovering in Example 13

### ISSUE THREAD

**Issue by dofet** [HomeSpan/HomeSpan#891]
Hello,

I'm trying to set up a windowcovering, using example 13 as a source, but I've observed a strange behaviour from the TargetPosition Characteristic value in this example.

`target=new Characteristic::TargetPosition(0);       // Window Shades have positions that range from 0 (fully lowered) to 100 (fully raised)`
`target->setRange(0,100,10);                         // set the allowable target-position range to 0-100 IN STEPS of 10`

target is supposed to be in incremental values of 10, but in HomeKit seems to allow every int values.
I've tried other accessories with range values, like fan rotationspeed in example 4, which seems to work correctly.

Am I the only to observe this behaviour ? Is it normal ?

**Comment by HomeSpan** [comment]
I just tried this out and can confirm the Home App no longer respects setRange().   The Eve for Home Kit app continues to only allow changes in the steps specified, but the Home App ignores.  Must be a change Apple made somewhat recently.

To be fair the original HAP-R2 spec states that only Characteristics with INT or FLOAT can change their min/max/step values.  This means step values will still work with Brightness (for a lightbulb) and Rotation Speed (for a fan), which are INT and FLOAT, respectively.  But CurrentPosition and TargetPosition are defined as UINT8, so in principle the Home App should ignore the mix/max/step requests.  They used to allow min/max/step changes for most numeric-based characteristics, but now it seems like the Home App finally caught up to the 2019 specs.

Thanks for catching this.  Since there is a chance that Apple reverts this new restriction back to prior practice in a future release, I'll make a note in the documentation, but still allow the user to set for now.

**Comment by dofet** [comment]
Ah ok, interesting. Thanks for the heads up.

Do you see any workaround to force a fixed number of positions ? Or is it better to work with the full range allowed by Apple ?

**Comment by HomeSpan** [comment]
One possibility would be to enforce the step sizes in the sketch itself.  For example, the user might request 42% as a target state.  After receiving this you could round to 40% and set the window shade accordingly.  Once set, you can then update both currentPosition and targetPosition, so that the Home App slider resets to 40%.

**Comment by dofet** [comment]
Ok thanks, I will try that
