### ISSUE TITLE
how to turn off the blinking led?

### ISSUE THREAD

**Issue by AAfetisov** [HomeSpan/HomeSpan#910]
is it possible to turn off the blinking blue led on esp32 wroom board?
I tried setting homeSpan.setStatusPin to different values and   homeSpan.setStatusPixel(0, 0, 0, 0), but nothing has helped so far. The blinking is really annoying at night

**Comment by HomeSpan** [comment]
What blinking blue LED?  Unless you specifically set a Status Pin, HomeSpan is not going to output anything to any LED.  You may have something else going on in your code.  Some ESP32's include an RGB NeoPixel that may be operating even if you don't access it with HomeSpan, though I don't know why it would be blinking.

What happens if you load a simple sketch that contains nothing but a single print statement (i.e. don't use HomeSpan at all).  Does the light still turn on?

**Comment by AAfetisov** [comment]
I did some testing and found out that it's a "feature" of the arduino version of the stock wifi library. Seems like no solution
http://esp32.io/viewtopic.php?t=41243&p=135816
