### ISSUE TITLE
Accessories talking to eachother

### ISSUE THREAD

**Issue by victornpb** [HomeSpan/HomeSpan#912]
How it the recommended way of one accessory action on another accessory.

global flags, some kind of event bus, global instances, passing instances to constructors, some kind of global list of instances?

**Comment by HomeSpan** [comment]
There's a tutorial on this: [External Reference](https://github.com/HomeSpan/HomeSpan/blob/master/docs/Tutorials.md#externalreference)

**Comment by felix6262** [comment]
when you place the struct for an accessory in diferent files, i did it like this. 
1. in the io.file you type something like this:  sensor=new DEV_Sensor();  instead of new DEV_HumSensor();
2. you include your extra file #include "DEV_Sensor.h"
3. in the io.file something like this: DEV_Sensor* Sensor = nullptr;
4. in the sensor.h file you put this #ifndef DEV_SENSOR_H #define DEV_SENSOR_H in the beginning and this at the end #endif
5. you create a global file like Globals.h and put something like the following in it:

#ifndef GLOBALS_H
#define GLOBALS_H
#include "DEV_Sensors.h"
extern DEV_Sensor *sensor;
#endif

6. you include the global file to you io.file and in that file you are looking for the information. 
7. then you have access to the data like this: float humidity = humSensor->hum->getVal();

Annoyingly complicated. Would like to read a nicer solution. :D

**Comment by HomeSpan** [comment]
Closing for now - please feel free to re-open if needed.
