### ISSUE TITLE
Understanding problem with bridge

### ISSUE THREAD

**Issue by felix6262** [HomeSpan/HomeSpan#914]
Hello, 

i tried  diffrent stuff with home span. Everything works as planned. But still im figuring out the difference between bridge or not. I mean obviously there is something with assiging names to the accessory. But is that all? Could i basicaly use the bridge everytime?

Could someone please try to explain the difference between bridge and not to me. 

And yes i read the examples, tutorials, etc. but still dont get it. 

Thanks!

**Comment by HomeSpan** [comment]
There's really not much of a difference, except for those points you noted.  I think the bridge concept is a historical artifact of the way Apple originally rolled out HomeKit.   I tend to use bridges more often than not since it's easier to add new Accessories without needing to unpair and re-pair, provided you don't mess with the existing Accessories.  But for a plain-vanilla light switch, I can't think of any practical differences between using a bridge or not.

**Comment by felix6262** [comment]
ah well thanks. then i'm going to use the bridge all the time, when i combinate more than one accessory.
