### ISSUE TITLE
BSSID support and create task for checkConnect()

### ISSUE THREAD

**Issue by ismail-ozturk** [HomeSpan/HomeSpan#955]
Hello, I have 3 access ponts in my house with the same SSID, but when the power goes out and comes back, Device connects to the remote accesspoint , I need to update it with the Accesspoint with a good RSSI value, for example by checking it 1 or 2 times.

What if I move the checkconnect method as a separate task and update the network scanning part according to bestrssi?

**Comment by HomeSpan** [comment]
That's a good idea.  Let me investigate further - might be something I can add to the library more generally.

**Comment by HomeSpan** [comment]
Thanks again for the suggestion - its was very timely since I was already in the process of refactoring some of the WiFi code to prepare for integrated Ethernet support.

I updated HomeSpan to ensure that it always connects to the access point with the strongest WiFi signal available when first booting (previously it simply connected to the first one found, regardless of RSSI) and I also created a few new functions for use with mesh-networks including one that enables HomeSpan to periodically rescan all access points within your configured SSID to determine if there is a stronger one available.  If so, it drops the WiFi connection to the current access point and automatically connects to the one with the stronger signal.  I think this should directly solve the issue above.

All the code (and new documentation) is available in the **dev** branch.  Please give it a try and let me know how it works.  I've tested on my own network with 4 access points by moving around my ESP32 when powered by battery.  As expected, it drops the connection and reconnects to the strongest access points whenever it finds a better one.

**Comment by ismail-ozturk** [comment]
I had prepared a structure in the same way after I created this post :) but I will try your code
If you want, I can send you the change I made in version 1.9.1 if you want to review it.

**Comment by ismail-ozturk** [comment]
Now I was reviewing your code
It is a very professional structure
Can I apply the current change in my own project for version 1.9.1?

**Comment by HomeSpan** [comment]
Feel free to add any of the changes to your own copy of 1.9.1 but it may take you some work since all of my changes are in the current 2.X branch.  I don't intent on updating the 1.X branch any further since launching 2.0.0.   Have you tried HomeSpan 2.0.0?

**Comment by ismail-ozturk** [comment]
I have mounted about 20 devices in my house and I used another HomeKit library, unfortunately it did not have the partition structure required for 2.0. So I will be able to UPDATE to 1.9.1 via OTA.

**Comment by HomeSpan** [comment]
Understood.  It's definitely a real problem that Espressif has so dramatically expanded the footprint for IDF-5 (now used by Arduino-ESP32, and hence used in the latest versions of HomeSpan).   I am considering creating a custom IDF library for use exclusively with HomeSpan that would hopefully have a smaller footprint so it can fit in a normal-size partition.  But that's a big project and something I'm likely to tackle in the near term.

**Comment by ismail-ozturk** [comment]
Hello Again, 
I applied the changes in dev for ver 1.9.1 .  but there is a problem. It keeps trying to connect but can't
![image](https://github.com/user-attachments/assets/6944355f-f4ac-439f-b56c-3cbeb65fba64)

**Comment by HomeSpan** [comment]
No, sorry.  The changes are too significant between 1.X and 2.X.

**Comment by HomeSpan** [comment]
Feature is now available in latest release v2.1.0.
